//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 08/04/2015 15:01:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.SB.Entities
{

    [DataContractAttribute(IsReference=true)]
    public partial class StatusTypeStructureTemplateDTO
    {
        #region Constructors
  
        public StatusTypeStructureTemplateDTO() {
        }

        public StatusTypeStructureTemplateDTO(global::System.Guid statusTypeStructureTemplateID, global::System.Guid statusTypeTemplateID, int statusTypeTemplateVersionNumber, global::System.Nullable<System.Guid> statusTypeValueTemplateID, int statusOrder, bool isStart, bool isEnd, StatusTypeTemplateDTO statusTypeTemplate, StatusTypeValueTemplateDTO statusTypeValueTemplate, List<StatusTypeStructureTransitionTemplateDTO> statusTypeStructureTransitionTemplates_CurrentStatusTypeStructureTemplateID, List<StatusTypeStructureTransitionTemplateDTO> statusTypeStructureTransitionTemplates_NextStatusTypeStructureTemplateID) {

          this.StatusTypeStructureTemplateID = statusTypeStructureTemplateID;
          this.StatusTypeTemplateID = statusTypeTemplateID;
          this.StatusTypeTemplateVersionNumber = statusTypeTemplateVersionNumber;
          this.StatusTypeValueTemplateID = statusTypeValueTemplateID;
          this.StatusOrder = statusOrder;
          this.IsStart = isStart;
          this.IsEnd = isEnd;
          this.StatusTypeTemplate = statusTypeTemplate;
          this.StatusTypeValueTemplate = statusTypeValueTemplate;
          this.StatusTypeStructureTransitionTemplates_CurrentStatusTypeStructureTemplateID = statusTypeStructureTransitionTemplates_CurrentStatusTypeStructureTemplateID;
          this.StatusTypeStructureTransitionTemplates_NextStatusTypeStructureTemplateID = statusTypeStructureTransitionTemplates_NextStatusTypeStructureTemplateID;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid StatusTypeStructureTemplateID { get; set; }

        [DataMember]
        public global::System.Guid StatusTypeTemplateID { get; set; }

        [DataMember]
        public int StatusTypeTemplateVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> StatusTypeValueTemplateID { get; set; }

        [DataMember]
        public int StatusOrder { get; set; }

        [DataMember]
        public bool IsStart { get; set; }

        [DataMember]
        public bool IsEnd { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public StatusTypeTemplateDTO StatusTypeTemplate { get; set; }

        [DataMember]
        public StatusTypeValueTemplateDTO StatusTypeValueTemplate { get; set; }

        [DataMember]
        public List<StatusTypeStructureTransitionTemplateDTO> StatusTypeStructureTransitionTemplates_CurrentStatusTypeStructureTemplateID { get; set; }

        [DataMember]
        public List<StatusTypeStructureTransitionTemplateDTO> StatusTypeStructureTransitionTemplates_NextStatusTypeStructureTemplateID { get; set; }

        #endregion
    }

}
