//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bec.DynamicForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSectionQuestion
    {
        public int FormSectionQuestionid { get; set; }
        public Nullable<int> FormSectionid { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public Nullable<int> SortingOrderNo { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public string QuestionNo { get; set; }
    }
}
