/* Data for the 'public.FieldDetailTemplate' table  (Records 1 - 121) */

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'003cfc9e-248c-11e4-b54b-87a269f02a60', E'LastName', E'Last Name', E'Last Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'005270fc-248b-11e4-b3cb-6b7e5b762ed0', E'BranchAdministrator', E'Branch Administrator', E'Branch Administrator', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'03bc9b54-248c-11e4-9be6-1774d6a73e68', E'Notifications', E'Notifications', E'Notifications', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'04039e10-248b-11e4-9e35-5ffed504b592', E'TotalRegulatedPractitioners', E'Total Regulated Practitioners', E'Total Regulated Practitioners', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0761d9dc-23a0-11e4-91aa-eb94305f8cc2', E'NoOfCompletionsPerMonth', E'Number of Completions Per Month', E'What is the average number of completions by your firm per month?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0773c2ea-248c-11e4-bea7-bf0bc49edde3', E'EmailAddress', E'Email address', E'Email address', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'082fe764-248b-11e4-98bd-237d8e9ac762', E'TotalStaff', E'Total Staff', E'Total Staff', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0abdb2da-248c-11e4-9799-cf88824f33de', E'UserType', E'User Type', E'User Type', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0c58ebbc-2484-11e4-9b6e-b79f671930da', E'AreYouRP', NULL, E'Are you a regulated practitioner?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0c5c8800-4949-11e4-994b-a74a823ede62', E'Price', E'Price', E'Price', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'0e6a0e2e-2469-11e4-9d59-e71b96bbab16', E'MiddleName', E'MiddleName', E'Middle Name(s)', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'103dbd40-248c-11e4-95cd-1f9d5ecd4eac', E'Branch', E'Branch', E'Branch', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'1103f142-4a23-11e4-b789-27a11ca088ef', E'Description', E'Product Description', E'Description', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password', E'Password', E'Password:', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'127433d4-246c-11e4-b882-7fd92c11d7d6', E'Gender', NULL, E'Gender', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'1436a2d6-248c-11e4-b260-2b3d2b1cb296', E'Regulator', E'Regulator', E'Regulator', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'1840c71c-248c-11e4-8a61-7f1b4dab42b9', E'RegulatorNumber', E'Regulator No', E'Regulator No', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'1877a618-2394-11e4-8a3e-e7ebb76a4fa0', E'PIIProvider', E'Personal Indemnity Insurance Provider', E'Your PII Insurance Provider', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'190fa302-23a1-11e4-90a2-db87167ddd13', E'DirectDialPhoneNumber', E'Direct Dial Phone NUmber', E'Direct Dial Phone Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'195a8292-4943-11e4-8b8c-8fde078625f0', E'OrderSummaryInfoLabel', E'Order Summary Info', E'More information about each product can be found by clicking on the individual items in ''Your Order Summary''', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'19e601b0-239f-11e4-aa31-9b060ca5599f', E'RegisteredCompanyNumber', E'Registered Company Number', E'Registered Company Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'1c57084a-2232-11e4-b658-b35c6c384846', E'CONameDetail', E'CO Name Detail', E'Please enter the Compliance Officer’s name as it appears on the regulator’s database.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'217bf9b4-4949-11e4-8c44-5f7c069b8167', E'Quantity', E'Quantity', E'Qty', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'24e7e0b4-2472-11e4-9d7f-3fb87d9ba808', E'DynamicSecurityQuestion', NULL, NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'29dac16e-2232-11e4-bcc5-875b01f49995', E'Title', E'Title', E'Title', E'Mr', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'2f978ec0-2232-11e4-8240-37b489a158b7', E'FirstName', E'FirstName', E'First Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'3401b966-23a1-11e4-a567-73d912572346', E'AccountName', E'Name of the Account', E'Name of the Account', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'349b52b2-2232-11e4-b03c-b3a634177c2c', E'LastName', E'LastName', E'Last Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'36440112-2486-11e4-b3f3-07797aecf3ea', E'ChangedAddress', NULL, E'Have you changed address in the last three years?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'3798cc58-246f-11e4-8593-c3204642af7f', E'AccountOpened', NULL, E'Account Opened', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'38c4a4d0-2393-11e4-8fd0-f764af083de5', E'FirmName', E'Firm Registered Name', E'Firm Name (registered name)', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Email', E'Email', E'Email', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'3c6513d2-246e-11e4-a2d4-8f5ec1e9af2a', E'AddressLabel', NULL, E'Please enter your registered home address details. Please note we require 3 years of property history.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'3d0ce938-239f-11e4-8c20-77181475b1a8', E'FirmVATRegistered', E'Firm VAT Registered', E'Is your Firm VAT registered?', E'Yes', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'3f1dd066-2232-11e4-bbea-afeb1da848d8', E'IamCO', E'User entring data on Registration is CO', E'I am the Compliance Officer', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1703, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'47960ca8-4948-11e4-886e-8745ccf03acd', E'CardExpiryMonth', E'Card Expiry Month', E'Expiry Date', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, True, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'47df58c6-2487-11e4-9b6b-8b64df9c95cb', E'IBANLabel', NULL, E'*IBAN (International Bank Account Number) and SWIFT numbers are only required for non UK bank accounts.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'4af5c964-4949-11e4-8026-fb02a4964985', E'Total', E'Total', E'Total', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'4dfc601c-2394-11e4-b761-1f84f307bfd8', E'PolicyNumber', E'PII Policy Number', E'Policy Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'4e3e0906-23a1-11e4-98c2-577e64469c59', E'SortCode', E'Sort Code', E'Sort Code', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, E'00-00-00');

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'507ec870-3451-11e4-9973-cffcabd7a34c', E'FirmCOForFinanceAndAdministration', E'Compliance Officer for Finance and Administration', E'Are you the Compliance Officer for Finance and Administration?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'5270026e-47ef-11e4-a3bb-bb1fdd63b4ee', E'RegistrationSummaryBranchesandUsers', E'Branches and Users on Registration Summary', E'You have setup the following branches and users to complete their registration', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'53a06e28-4946-11e4-b011-678a74377bb4', E'CardType', E'Card Type', E'Card Type', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'587a9c4c-246c-11e4-9acc-7bcac2491812', E'AddressOutsideUK', NULL, E'My address is outside the UK', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1703, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'5a253f4e-47f2-11e4-8dc6-efcd324a0964', E'RegistrationSummaryEmail', E'Registration Summary Email', E'I would like an email of the above summary', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'5e55192e-47f5-11e4-9818-6790f40ed2a8', E'MembershipLabel', NULL, E'Please select if you are a member of any of the following:', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'RegulatorNumber', E'RegulatorNumber', E'RegulatorNumber', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'62226f40-2232-11e4-93e3-cf638efa91ae', E'IsCOOfficeHeadOffice', E'IsCOOfficeHeadOffice', E'The Compliance Officer’s Office Address is the Head Office as listed on the regulator database.', E'Yes', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'652bccc2-239f-11e4-8bfd-77a5e7b1db1a', E'ForgotUsername', NULL, E'Forgot Username', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1706, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'65e4aa4e-2232-11e4-9e7b-03c14854ca01', E'FindAddressLabel', E'FindAddressLabel', E'Please enter postcode and building number/company name then click ‘Find Address’', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, 1801, E'info.png', False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'67da65d6-23b4-11e4-9ad7-1f37d978616f', E'SecurityQuestion2', NULL, E'Question 2', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'68965c64-4948-11e4-8b55-7fceae824049', E'CardExpiryYear', E'Card Expiry Year', NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'6aebf40c-2232-11e4-8bf3-63d0abf3183d', E'Postcode', E'Postcode', E'Postcode', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'6c3a5f82-246d-11e4-8b01-afb04e946c53', E'TelephoneType', NULL, NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'6f4dbd6e-2232-11e4-b407-b702edef2662', E'HouseNumber/Name', E'HouseNumber/Name', E'House Number/Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'6fcb33e6-23a1-11e4-a590-5b4d1fad9964', E'AccountNumber', E'Account Number', E'Account Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'70514602-496c-11e4-8061-0702c3031f0b', E'CardNumber', E'Card Number', E'Card Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'724a220a-239f-11e4-b1c2-67caf93b9dfd', E'VATNumber', E'VAT Number', E'VAT Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'724edb60-2232-11e4-b15d-d7d3995a864b', E'AdditionalAddressInformation', E'AdditionalAddressInformation', E'Additional Address Information', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'77bb228e-2232-11e4-b306-ab26a05fe9db', E'AddressLine1', E'AddressLine1', E'Full Address', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'7b60d686-2232-11e4-8e5c-033886926b0e', E'AddressLine2', E'AddressLine2', NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'7ea60f16-246f-11e4-82d5-eba428934b46', E'MonthText', NULL, E'Month', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'7efd5fe4-4942-11e4-8c3c-d397c8d143b3', E'PaymentMethodLabel', E'Payment Method', E'Please enter your payment method for the selectiions you have made.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'7f002a12-2232-11e4-9dc8-a7282c55a9e8', E'Town/City', E'Holds PostTown returned from PostCodeAnywhere', NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'81194718-2393-11e4-b1e5-cf6a2b3ed7d2', E'TradingName', E'Trading Name', E'Trading Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'83eedaa0-2232-11e4-b7eb-1f0168fc76ca', E'County', E'County', NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'86748d74-2232-11e4-9e1d-d3ffa727a5ed', E'Country', E'Country', NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'8d00d582-2488-11e4-b5ab-0bf5909ff25c', E'BranchesSetUpText', E'Branches SetUp Text', E'Please setup your conveyancing branches below (you can add your staff to these branches on the next page). Use this page to approve/amend/or delete your branches. You can also access this page at a later time via your dashboard once you have completed your registration process. Anything that requires your immediate attention will appear in red text in the ‘Notifications’ column', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'8fc55546-23a1-11e4-81b4-07d95b4b3b27', E'AddAnotherClientAccount', E'Add another Client Account used for conveyancing', E'Add another client account used for conveyancing?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'92b89816-2488-11e4-809d-c7750a164755', E'UserSetUpText', E'User SetUp Text', E'Please setup your conveyancing users below. Use this page to approve / amend / or delete your users. You must add at least 1 Regulated Practitioner to each branch. You can also access this page at a later time via your dashboard once you have completed the registration process. Anything that requires your immediate attention will appear in red text in the ‘Notifications’ column.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'92f561aa-2394-11e4-aa0d-9b9e315b3eab', E'RenewalDate', E'PII Policy Renewal Date', E'Renewal Date', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'93c2ad3e-23b4-11e4-b3b8-0b14de35c378', E'AnswerToSecurityQuestion', NULL, E'Answer to question 1', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'94dc3664-239f-11e4-a411-0b54dea20d32', E'NoOfRegulatedPartners', E'Number of Regulated Partners / Directors', E'How many regulated partners / directors does your firm have?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'993466b6-2488-11e4-985a-ff659374eaf4', E'UserManagementText', E'User Management Text', E'User Management ', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'9b43043a-23bb-11e4-936f-13c5bbbcbab9', E'CreateLoginInfoLabel', NULL, E'Thank you for logging on to the Safe Move Scheme. For your protection please complete the form below to create your own secure login details.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, 1801, E'info.png', False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'5867e690-65aa-11e4-b2b0-97bf86dc2dfe', E'CreateLoginInfoLabel1', E'CreateLoginInfoLabel1', E'You will then need to click the ‘Log Off’ button above then you will receive a notification so you can login using your new secure login details to complete your registration.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'9bc78824-4948-11e4-b1a5-d38960935800', E'CVC', E'CVC', E'CVC', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'9ffe8fe2-239f-11e4-949a-cb61b48e2c73', E'ForgotPassword', NULL, E'Forgot Password', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1706, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'a19952c6-246f-11e4-8b0c-63c481de2de6', E'IBANNumber', NULL, E'IBAN Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'a373c578-246e-11e4-aa6e-6f6785a8c193', E'HowLongYouLivedHereLabel', NULL, E'How long have you lived here?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'a455c44a-2393-11e4-8b9d-c71eaa64022e', E'Website', E'Website', E'Website', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'a6107ba6-2490-11e4-bac9-c3aac09ccce1', E'AreYouCO', E'Are you Compliance Officer', E'Are you the compliance officer', E'Are you the compliance officer at your law firm?', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'aa6ac64e-2232-11e4-9418-43090b174057', E'RegisterSubmitLabel', E'Register Submit Label', E'On submission of this form your Compliance Officer will be sent an email with further instructions on how to complete the registration of your firm on the Safe Move Scheme.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'ac587fb0-4946-11e4-b5a3-fbfa661bcfbc', E'CardholderName', E'Cardholder Name', E'Cardholders Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'ad8fe35e-2232-11e4-a00c-1b114492e175', E'RejectionReason', E'Rejection Reason', E'Reason for Rejection', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'aef4cf7a-23b3-11e4-9e13-bf16b41d2b15', E'CreateLoginConfirmPassword', NULL, E'Please confirm your password', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'afca193c-2232-11e4-9b7e-c3f590179310', E'BranchName', E'Branch Name', E'Branch Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'b4b5f420-2232-11e4-aab3-effe75391f5f', E'OfficeType', E'OfficeType', E'OfficeType', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'b553a0c6-239f-11e4-99e6-b7439b268ad0', E'NoOfRegulatedPractitioners', E'Number of Regulated Practitioners', E'Number of regulated practitioners in firm?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'b76e7520-2232-11e4-9852-fb71f03fe88c', E'DXNumber', E'DX Number', E'DX Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'b7f776dc-246b-11e4-82bd-07d2e9752208', E'QualifiedDate', NULL, E'Date you Qualified', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, E'99/99/9999');

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'bb50efee-246f-11e4-9c38-7f2086e22c21', E'SWIFT/BICNumber', NULL, E'SWIFT/BIC Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', E'BranchStatus', E'Branch Status', E'Branch Status', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'bce35af6-23b4-11e4-ae0d-ffc0a75e8518', E'AnswerToSecurityQuestion2', NULL, E'Answer to question 2', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'be616b9e-2232-11e4-b30b-a70d2e4c4140', E'Notifications', E'Notifications', E'Notifications', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c0ebdea8-2232-11e4-ad2d-43db229a90ed', E'RejectionReasonComments', E'Rejection Reason Comments', E'Please enter your reason for rejection', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c1127aba-246a-11e4-b066-ebd750d2e88d', E'Nationality', NULL, E'Nationality', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c3f92eac-2232-11e4-a4f1-1fc90b644a11', E'Branch', E'Branch', E'Branch', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c49aeb7c-3a59-11e4-89b9-83b8ffd40e87', E'PreviousAddressLabel', E'PreviousAddressLabel', E'Please enter details of your previous adresses over the last 3 years', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c5f6bd52-2393-11e4-96b2-9f31e5def021', E'Regulator', E'Regulator', E'Who is your regulator?', E'Please Select', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'c78cc0b0-2232-11e4-ac12-1fd8a2b704ae', E'UserType', E'User Type', E'User Type', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'cb07bfc4-2232-11e4-b495-37bb7af0d6fe', E'UserStatus', E'User Status', E'User Status', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'cdd4201c-239f-11e4-9c27-7307f00ffba4', E'NoOfStaff', E'Number of staff', E'How many staff does your firm employ?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'd23cffce-246d-11e4-b97b-1b2ce0c0121d', E'AddTelephoneNumber', NULL, E'Add telephone number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'd3576b3c-246e-11e4-a17e-d30ff304c125', E'Years', NULL, NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'd75e4a94-2486-11e4-85ea-1f3cb5b23ed9', E'IDPlusLabel', NULL, E'ID+ uses personal bank account data to raise the security level of out user ID verification to enable you to perform ''trusted'' functions. Please enter the sort code and bank account number of a bank account registered to your home address. Your bank details are only used for verifying your identity.', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1701, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'dae9b67a-47f5-11e4-8300-232f210ebb09', E'MembershipItems', NULL, NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'dc79fbb2-2469-11e4-bc2d-3ba50d3cd4ef', E'DOB', NULL, E'Date of birth', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, E'99/99/9999');

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'dd989bbe-239e-11e4-8ff1-c7e4f217a84b', E'Username', E'Username', E'Username:', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'e1b0484a-23b3-11e4-951a-07b35f59b36a', E'SecurityQuestion1', NULL, E'Question 1', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'e1d9f18c-239e-11e4-869f-776524cf5025', E'FirmCompaniesHouseRegistered', E'Firm Registered at Companies House', E'Is your Firm registered at Companies House?', E'Yes', True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'e27fc098-246c-11e4-b8a6-6b1ebb088486', E'TelephoneNumber', NULL, E'Primary Telephone No', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'e3447ef0-4948-11e4-b27b-d7db85bec177', E'Product', E'Product', E'Product', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'ee59a8d8-23a0-11e4-9d7f-ab33d263c791', E'OfficePhoneNumber', E'Office Phone Number', E'Office Phone Number', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1702, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'f4337022-47ef-11e4-b21e-8b1b15cd89a3', E'RegistrationSummaryBranchesandUsersFooter', E'Registration Summary Branchesa nd Users Footer', E'You can add branches or users and amend your firms details in your administration area from your Safe Move Scheme dashboard', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, NULL, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'f457e7b2-246e-11e4-9677-7bbd9742d303', E'Months', NULL, NULL, NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1705, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'f4ae6efe-248a-11e4-9b32-3b82fff23e6a', E'BranchName', E'Branch Name', E'Branch Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'f61e841c-248b-11e4-ac49-c7eb955572d4', E'Title', E'Title', E'Title', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'f8deb092-248a-11e4-8193-331b0c31c46b', E'Notifications', E'Notifications', E'Notifications', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'fa39aad4-246a-11e4-8be5-4fb468c95486', E'Namechange', NULL, E'Have you changed name in the last 3 years?', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, True, 1704, NULL, NULL, False, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'fc9e1708-248b-11e4-837c-3b2ed21fab78', E'FirstName', E'First Name', E'First Name', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);

INSERT INTO public."FieldDetailTemplate" ("FieldDetailTemplateID", "Name", "Description", "FieldLabelValue", "DefaultValue", "IsActive", "IsDeleted", "ToolTipValue", "ToolTipHTML", "ToolTipIsHTML", "InformationValue", "InformationHTML", "InformationIsHTML", "HelpValue", "HelpHTML", "HelpIsHTML", "IsSecuredByClaim", "IsGlobal", "FieldTypeID", "IconAlignmentTypeID", "IconFileName", "IsGridColumn", "FieldMask")
VALUES (E'fcaa9128-248a-11e4-a4ef-4b107df30f13', E'BranchType', E'Branch Type', E'Branch Type', NULL, True, False, NULL, NULL, False, NULL, NULL, False, NULL, NULL, False, False, False, NULL, NULL, NULL, True, NULL);