/* Data for the 'public.InterfacePanelValidationTemplate' table  (Records 1 - 123) */

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'009fa852-26bd-11e4-a421-eb1800e1f115', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20013', True, False, False, E'FirstData_Gateway_20013');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'026652c2-26bc-11e4-bf46-57b070805b73', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'67', True, False, False, E'FirstData_CardIssuer_67');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'0377a846-31e3-11e4-811e-077e72aae07f', E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, 1, E'Invalid Username', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'InvalidUsername');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'059ed7fc-26bc-11e4-98ff-878aab131be1', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'75', True, False, False, E'FirstData_CardIssuer_75');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'0848f08c-335f-11e4-af3d-6fe35674cb06', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'The characters that you entered didn’t match the verification code. Please try again.', NULL, NULL, NULL, NULL, NULL, True, False, True, E'CaptchaMismatch');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'090eb808-26bc-11e4-a3bb-b3fe0752b53f', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'82', True, False, False, E'FirstData_CardIssuer_82');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'098ac17e-2ebd-11e4-b721-277a11abdfab', E'29c9159e-2391-11e4-953b-874efbbdf816', 1, 1, E'The answer you provided does not match the answer you previously answered', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'AnswerDoesnotMatch');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'0c676ab8-26bc-11e4-8b3e-13d29446a3eb', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'90', True, False, False, E'FirstData_CardIssuer_90');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'0feb4b00-26bc-11e4-9419-43c70f641876', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'91', True, False, False, E'FirstData_CardIssuer_91');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'1489fc06-26bc-11e4-9f25-fb0b2e504e75', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'92', True, False, False, E'FirstData_CardIssuer_92');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'17dbd0d2-26bc-11e4-90ed-5b5fca5bcf59', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'93', True, False, False, E'FirstData_CardIssuer_93');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'1b8a7e0e-26bc-11e4-be30-9f2516aac773', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, NULL, E'Your payment has been declined as they match those of another recent transaction. Please contact <a href=\\\"mailto:support@safemovescheme.org\\\">support@safemovescheme.org</a>  for further assistance.', NULL, NULL, NULL, NULL, E'94', True, False, True, E'FirstData_CardIssuer_94');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'21d1ee8c-26bc-11e4-90b2-33416650a169', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'96', True, False, False, E'FirstData_CardIssuer_96');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'2360e7b8-2490-11e4-92aa-f738de5b141c', E'5cc14b72-2393-11e4-8e99-1773c703c71a', 1, 1, E'Passwords do not match, please check and try again', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'PasswordsDoNotMatch');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'25870436-26bc-11e4-a61a-0fa078560970', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'1', True, False, False, E'FirstData_Gateway_1');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'260e692c-26bb-11e4-a8d2-f79c63772f47', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'2', True, False, False, E'FirstData_CardIssuer_2');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'291f454a-26bc-11e4-a5b6-6368f2bde41c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'2', True, False, False, E'FirstData_Gateway_2');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'2d7e49c4-26bc-11e4-b1d2-4b67353474a6', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'100', True, False, False, E'FirstData_Gateway_100');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'31b9c41e-26bc-11e4-9084-7318aba8562c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'1003', True, False, False, E'FirstData_Gateway_1003');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'323b0f84-2ebd-11e4-83c3-775caa3083bf', E'29c9159e-2391-11e4-953b-874efbbdf816', 1, 1, E'Invalid Email', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'InvalidEmail');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'353f15a8-26bc-11e4-a93a-1be30f141dfc', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'2000', True, False, False, E'FirstData_Gateway_2000');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'38aeb6f8-26bc-11e4-b9a9-3760dee3f9fb', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'2100', True, False, False, E'FirstData_Gateway_2100');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'3bdab968-26bb-11e4-99df-7373c47a1915', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'3', True, False, False, E'FirstData_CardIssuer_3');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'3c67af2a-26bc-11e4-b1b5-93085bdf65a2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'2200', True, False, False, E'FirstData_Gateway_2200');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'3f6cbb48-23a1-11e4-a46d-abcdaec5062e', E'7f6b9150-2235-11e4-87a7-674ef85109a7', 1, 1, NULL, E'<!DOCTYPE html>\r\n<html>\r\n<body><P>The password you have entered has expired. Please click <a href=\"http://localhost/Bec.TargetFramework.UI.Web/STSLogin/ForgottenPassword\" target=\"_blank\">here</a> for a new password to be sent.</P></body>\r\n</html>', NULL, NULL, NULL, NULL, NULL, True, False, True, E'ExpiredPassword');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'3fa07402-26bb-11e4-8731-6f93b0894524', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'4', True, False, False, E'FirstData_CardIssuer_4');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'3fd20368-26bc-11e4-9014-ab811406b6a2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'2300', True, False, False, E'FirstData_Gateway_2300');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'44bcc840-26bc-11e4-a5e6-3746302a81d1', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'2301', True, False, False, E'FirstData_Gateway_2301');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'44f6490e-26bb-11e4-aba0-53bcc4a06fdb', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'5', True, False, False, E'FirstData_CardIssuer_5');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'483502f8-26bc-11e4-ac16-3f50c2c5d3ae', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'2302', True, False, False, E'FirstData_Gateway_2302');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'4b9720ca-26bc-11e4-8766-5f328be10498', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'2303', True, False, False, E'FirstData_Gateway_2303');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'4ee54324-26bc-11e4-8049-039d301eadd7', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', NULL, NULL, NULL, NULL, NULL, E'2304', True, False, False, E'FirstData_Gateway_2304');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5224492c-26bc-11e4-8ccb-df89cc2064ee', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'5000', True, False, False, E'FirstData_Gateway_5000');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5229cf1a-26bb-11e4-a4f8-27b8829abb54', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'6', True, False, False, E'FirstData_CardIssuer_6');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'561d1770-26bc-11e4-8017-57d6816f00d5', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'5001', True, False, False, E'FirstData_Gateway_5001');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5830e8ee-26bb-11e4-9de6-d34bd8d67047', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'7', True, False, False, E'FirstData_CardIssuer_7');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5bcc1398-26bb-11e4-bc6c-6bf26570363a', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'9', True, False, False, E'FirstData_CardIssuer_9');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5c44a082-26bc-11e4-85d9-6fb27bbe481d', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'5002', True, False, False, E'FirstData_Gateway_5002');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'5f0a0c04-26bb-11e4-8420-db796b03757a', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'12', True, False, False, E'FirstData_CardIssuer_12');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'60695a54-26bc-11e4-8a14-4f9450cfeb2a', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, NULL, E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', NULL, NULL, NULL, NULL, E'5003', True, False, True, E'FirstData_Gateway_5003');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'622fc392-26bb-11e4-afc3-c3e7611a96b0', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'13', True, False, False, E'FirstData_CardIssuer_13');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'65bdabbe-26bb-11e4-b3a7-cf183cc4b4ad', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'14', True, False, False, E'FirstData_CardIssuer_14');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'65cae5d0-26bc-11e4-9f85-7b565678e388', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, NULL, E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', NULL, NULL, NULL, NULL, E'5004', True, False, True, E'FirstData_Gateway_5004');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'6814dd34-26ba-11e4-926d-e7da378ac10d', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'1', True, False, False, E'FirstData_CardIssuer_1');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'6975ae0a-26bb-11e4-bbba-1fed59d85936', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'15', True, False, False, E'FirstData_CardIssuer_15');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'6b91bc3c-26bc-11e4-a2fe-bf712c90457e', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Form validation should prevent this, however:\\nYour payment has been declined as the details provided are invalid. Please check these details and try again.\\n', NULL, NULL, NULL, NULL, NULL, E'5005', True, False, False, E'FirstData_Gateway_5005');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'6cf8c1ac-26bb-11e4-9056-a314f9ae1410', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'We have been unable to process your payment at this time. Please check your details and try again. You have not been charged.', NULL, NULL, NULL, NULL, NULL, E'19', True, False, False, E'FirstData_CardIssuer_19');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'703de702-26bb-11e4-8f37-e7fae36504cc', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'21', True, False, False, E'FirstData_CardIssuer_21');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'72680b24-26bc-11e4-8fb9-773507b5ee25', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'5006', True, False, False, E'FirstData_Gateway_5006');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'74081006-26bb-11e4-9a35-af497ebef68c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'We have been unable to process your payment at this time. Please check your details and try again. You have not been charged.', NULL, NULL, NULL, NULL, NULL, E'22', True, False, False, E'FirstData_CardIssuer_22');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'77bcde34-26bb-11e4-895f-23289e070a11', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'23', True, False, False, E'FirstData_CardIssuer_23');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'7aa47d9a-26bc-11e4-8bf4-4f3195515f12', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'5007', True, False, False, E'FirstData_Gateway_5007');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'7c3bf15c-26bb-11e4-8783-9bd6925743e2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'25', True, False, False, E'FirstData_CardIssuer_25');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'7f652c7c-26bb-11e4-b4d6-d7235dc973e2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'30', True, False, False, E'FirstData_CardIssuer_30');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'7f723628-26bc-11e4-968b-4b369ea84c5b', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'5008', True, False, False, E'FirstData_Gateway_5008');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'82b1cc6e-26bb-11e4-8809-e3e144203029', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'31', True, False, False, E'FirstData_CardIssuer_31');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'83dea0ec-2483-11e4-8c49-ef53032e32e4', E'759a0024-2237-11e4-b86b-db81260b98c5', 1, 1, NULL, E'The details you have submitted for your Compliance Officer match with those of a Compliance Officer at another law firm on the Safe Move Scheme. \r\n\r\n<CO Title> <CO first name> <CO last name>  \r\n<CO firm name> (<CO firm trading name>)\r\n<CO regulator> \"number\" <CO regulator number>\r\n<CO office address>\r\n\r\nIf you would like to update your firm details to match this please click ''Update'' button below. Alternatively click ''Cancel'' and amend the Compliance Officer''s details to the correct values.\r\n', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_FirmDetails_COAlreadyExists');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'860bd8fa-26bb-11e4-a7f9-0f1f25ab532b', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', NULL, NULL, NULL, NULL, NULL, E'33', True, False, False, E'FirstData_CardIssuer_33');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'87befdb6-26bc-11e4-8371-07b29c5ebf6e', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'5150', True, False, False, E'FirstData_Gateway_5150');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'895ae9d8-26bb-11e4-b283-1bdf107a9aaa', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'34', True, False, False, E'FirstData_CardIssuer_34');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'8c296c4c-26bc-11e4-b9fc-53ec9d68eb7e', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'5999', True, False, False, E'FirstData_Gateway_5999');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'8ccc012e-26bb-11e4-9313-6ffb34bdf20c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'35', True, False, False, E'FirstData_CardIssuer_35');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'8eed381c-2484-11e4-aaaa-37c3d43b966b', E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, 1, E'“Sorry the details you have submitted do not match the Compliance Officer details at the SRA using the ‘Find A Solicitor’ database.”', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'STS_FirmDetails_CO_SRAConflict');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'8f681c46-26bc-11e4-a36d-27356ff2422d', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'10101', True, False, False, E'FirstData_Gateway_10101');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'905f8da6-26bb-11e4-b769-23934acf0b51', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'36', True, False, False, E'FirstData_CardIssuer_36');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'90a46606-31e2-11e4-b700-9fcab39fa2f3', E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, 1, E'A link to create a new password has been sent to your registered Email Address.', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'PasswordResetLinkEmailSent');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'92d7c4f8-26bc-11e4-aa7a-2ba3dfe2e7c0', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'10501', True, False, False, E'FirstData_Gateway_10501');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'960fbbb8-26bb-11e4-a95b-27669659c2ca', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'37', True, False, False, E'FirstData_CardIssuer_37');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'97dab9e8-5e9c-11e4-a011-8f438754d247', E'29c9159e-2391-11e4-953b-874efbbdf816', 1, 1, E'You have entered the wrong credentials 3 times and this has locked the system for 30 minutes.', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'ForgotUsernameRequestLockout');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'9857023e-552b-11e4-aa6c-f72f2bda67fe', E'f4143372-23b1-11e4-b867-7777db91cbfc', 1, 1, E'Please enter addresses for 3 years', NULL, NULL, NULL, NULL, NULL, NULL, True, False, NULL, E'AddressYearsValid');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'9c51e294-26bb-11e4-b9c6-5fd457dc0e8c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'38', True, False, False, E'FirstData_CardIssuer_38');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'9fab7b58-26bb-11e4-aa51-5f502763fd1c', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'39', True, False, False, E'FirstData_CardIssuer_39');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'a3805744-26bb-11e4-94d2-7b501c81db5b', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'40', True, False, False, E'FirstData_CardIssuer_40');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'a6f76020-26bb-11e4-b1ff-bb0354a79fc0', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'41', True, False, False, E'FirstData_CardIssuer_41');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'aa6ac64e-2232-11e4-9418-43090b174057', E'a2d81918-2232-11e4-b774-3b0341b43a3e', 1, 1, E'No match returned, please enter your address manually in the fields provided or try again', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'AddressServiceNoRecord');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'aa885758-26bb-11e4-8984-ef9b262c1e73', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'42', True, False, False, E'FirstData_CardIssuer_42');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'ad8fe35e-2232-11e4-a00c-1b114492e175', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'A compliance officer with these details already exists on the Safe Move Scheme. If you believe this to be in error please contact<a href=\"mailto:support@safemovescheme.org\">support@safemovescheme.org</a> ', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_DuplicateCO');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'af74c976-26bc-11e4-80f0-37a9560b0853', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'10502', True, False, False, E'FirstData_Gateway_10502');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b00a03de-26bb-11e4-bf06-3be03e4b7676', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'43', True, False, False, E'FirstData_CardIssuer_43');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b2affa84-26bc-11e4-8f0d-83b75af204f2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'10503', True, False, False, E'FirstData_Gateway_10503');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b3c3aebc-26bb-11e4-8b88-d30ca027b1a4', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'44', True, False, False, E'FirstData_CardIssuer_44');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b6437fe0-26bc-11e4-a120-f7bd1fbe75bd', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'10801', True, False, False, E'FirstData_Gateway_10801');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b8f934b0-26bb-11e4-bf81-2fb8f3810c69', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'51', True, False, False, E'FirstData_CardIssuer_51');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'b9b54d02-26bc-11e4-a4ef-9baae38acdbf', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'11001', True, False, False, E'FirstData_Gateway_11001');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'bc944038-26bb-11e4-acf7-434d4f9193c0', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'52', True, False, False, E'FirstData_CardIssuer_52');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'bdb10144-26bc-11e4-a6df-9ffcf8cf21cd', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'11101', True, False, False, E'FirstData_Gateway_11101');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c001653e-26bb-11e4-b26c-7b5686486e7b', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'53', True, False, False, E'FirstData_CardIssuer_53');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c166d926-26bc-11e4-9053-5ff5bfb6bdc7', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'11201', True, False, False, E'FirstData_Gateway_11201');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c3f92eac-2232-11e4-a4f1-1fc90b644a11', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'A compliance officer already exists on the Safe Move Scheme for this Firm. If you believe this to be in error please contact <a href=\"mailto:support@safemovescheme.org\">support@safemovescheme.org</a> ', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_AlreadyExistingCO');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c56fd518-26bc-11e4-bd22-4b2e65af130f', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'N/A', NULL, NULL, NULL, NULL, NULL, E'11202', True, False, False, E'FirstData_Gateway_11202');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c6c952fa-26bb-11e4-b4b1-b7c7a3ab6448', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', NULL, NULL, NULL, NULL, NULL, E'54', True, False, False, E'FirstData_CardIssuer_54');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c78cc0b0-2232-11e4-ac12-1fd8a2b704ae', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'The details you have entered already exist on the Safe Move Scheme and belong to the Compliance Officer at <<Registered CO Firm Name>>. Please check the details you have entered and try again', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_AnotherFirmCO');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c894c22c-31e2-11e4-9856-7bfca8e97d8d', E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, 1, E'The answer you provided does not match the answer you previously answered', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'AnswerDoesnotMatch');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'c9567aec-26bc-11e4-aec8-7fee2ab22679', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20000', True, False, False, E'FirstData_Gateway_20000');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'cb07bfc4-2232-11e4-b495-37bb7af0d6fe', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'Sorry the details you have submitted do not match the Compliance Officer details at the SRA using the ''Find A Solicitor'' database. Please check your details and re-submit or take corrective action with the SRA. If you are sure that the details you have provided are correct and match the SRA database then please contact <a href=\"mailto:support@safemovescheme.org\">support@safemovescheme.org</a>  for further assistance.”', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_COSRA');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'cc0343de-5e9c-11e4-910b-6f7c50f5a14d', E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, 1, E'You have entered the wrong credentials 3 times and this has locked the system for 30 minutes.', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'ForgotPasswordRequestLockout');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'cd24bc24-26bc-11e4-b77e-6b65f86465f5', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20001', True, False, False, E'FirstData_Gateway_20001');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'cdf665dc-2ebc-11e4-b6a2-3bfbe82a2dfa', E'29c9159e-2391-11e4-953b-874efbbdf816', 1, 1, E'Your username has been sent to your registered email address', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'UsernameSent');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'cf242836-2232-11e4-ac66-7f6de99930b1', E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, 1, NULL, E'Sorry the details you have submitted do not match the branch details at the SRA using the ‘Find A Solicitor’ database. Please check the branch details and re-submit or take corrective action with the SRA. If you are sure that the branch details you have provided are correct and match the SRA database then please contact <a href=\"mailto:support@safemovescheme.org\">support@safemovescheme.org</a>  for further assistance.', NULL, NULL, NULL, NULL, NULL, True, False, True, E'STS_BranchSRA');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'd0b694b6-26bc-11e4-a828-effc6e17e19f', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20002', True, False, False, E'FirstData_Gateway_20002');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'd3e56e6a-26bb-11e4-98b1-d7e655594498', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'55', True, False, False, E'FirstData_CardIssuer_55');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'd712e846-26bc-11e4-bf86-3bd055095306', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'20003', True, False, False, E'FirstData_Gateway_20003');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'd7c3912e-26bb-11e4-89e5-db8298a7fd80', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'56', True, False, False, E'FirstData_CardIssuer_56');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'd7f7d212-248c-11e4-bbe9-e7e59ff8c99d', E'a76467f8-2236-11e4-a090-2b2b425d524b', 1, 1, E'Password do not match, please check and try again', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'PasswordsDoNotMatch');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'da8afb3a-26bc-11e4-9c21-535bb39e0196', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20004', True, False, False, E'FirstData_Gateway_20004');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'dda96758-26bb-11e4-8e8c-9f57bcefb108', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'57', True, False, False, E'FirstData_CardIssuer_57');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'df2b4384-26bc-11e4-8eb2-37f93e503206', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20005', True, False, False, E'FirstData_Gateway_20005');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'e1642f36-26bb-11e4-a8b4-7fa30a176316', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'58', True, False, False, E'FirstData_CardIssuer_58');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'e3ba7bd6-26bc-11e4-bef7-a3c0d7450e64', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20006', True, False, False, E'FirstData_Gateway_20006');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'e4bb813e-26bb-11e4-b89e-8b9f3903b472', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'59', True, False, False, E'FirstData_CardIssuer_59');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'e73611b2-26bc-11e4-98b2-73c6c5ae705a', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20007', True, False, False, E'FirstData_Gateway_20007');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'e85e08d4-26bb-11e4-800b-3b2f8efcc0f9', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'60', True, False, False, E'FirstData_CardIssuer_60');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'eb4994fe-26bc-11e4-88f3-cf15449de540', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20008', True, False, False, E'FirstData_Gateway_20008');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'efd2627c-26bb-11e4-a3c0-e3cb1cfe3406', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'61', True, False, False, E'FirstData_CardIssuer_61');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'f1246bce-26bc-11e4-93d6-0336bb773cd2', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'20009', True, False, False, E'FirstData_Gateway_20009');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'f44c9e8a-26bb-11e4-a702-27f547373a77', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'62', True, False, False, E'FirstData_CardIssuer_62');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'f51526c4-26bc-11e4-996d-63fd43c7d879', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'20010', True, False, False, E'FirstData_Gateway_20010');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'f7a0983e-26bb-11e4-a2fa-eb06303b46f3', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'63', True, False, False, E'FirstData_CardIssuer_63');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'f90c22fa-26bc-11e4-ae4d-970502f2c1f7', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20011', True, False, False, E'FirstData_Gateway_20011');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'fb63f254-26bb-11e4-9aa5-9f93e528b076', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', NULL, NULL, NULL, NULL, NULL, E'64', True, False, False, E'FirstData_CardIssuer_64');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'fc9aef0a-26bc-11e4-afe2-7f2e101abd65', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', NULL, NULL, NULL, NULL, NULL, E'20012', True, False, False, E'FirstData_Gateway_20012');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'fe955fda-23aa-11e4-969d-ab5db90ee067', E'7f6b9150-2235-11e4-87a7-674ef85109a7', 1, 1, E'Username or Password is incorrect', NULL, NULL, NULL, NULL, NULL, NULL, True, False, False, E'IncorrectUsernameorPassword');

INSERT INTO public."InterfacePanelValidationTemplate" ("InterfacePanelValidationTemplateID", "InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelValidationTemplateVersionNumber", "OverrideValidationMessage", "OverrideValidationMessageHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "ValidationSubCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "OverrideValidationIsHTML", "InterfacePanelValidationTemplateName")
VALUES (E'fec6ff2c-26bb-11e4-a4a9-0757f9740827', E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, 1, E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', NULL, NULL, NULL, NULL, NULL, E'66', True, False, False, E'FirstData_CardIssuer_66');