/* Data for the 'public.InterfacePanelFieldDetailValidationTemplate' table  (Records 1 - 74) */

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password must contain at least 1 capital letter', NULL, False, NULL, NULL, NULL, NULL, True, False, E'00f3ca9c-2e90-11e4-b359-d3972ab9cbeb', NULL, E'MissingCapitalLetter');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'f4143372-23b1-11e4-b867-7777db91cbfc', 1, 1, E'dc79fbb2-2469-11e4-bc2d-3ba50d3cd4ef', E'Date of birth cannot be in the future, please re-enter', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'020551ba-2497-11e4-99ea-6fa318bcfe18', NULL, E'FutureDate');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Regulator Number is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'029c6bfa-2473-11e4-a5ca-cb62b28199d1', NULL, E'RegulatorNumberRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'c3f92eac-2232-11e4-a4f1-1fc90b644a11', E'Branch is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'0a829358-2473-11e4-b75d-b72b659b7659', NULL, E'BranchRequiredNULL');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'5e3e342a-2392-11e4-ad58-3fab4d0f9210', 1, 1, E'93c2ad3e-23b4-11e4-b3b8-0b14de35c378', E'The answer you provided does not match the answer you previously answered', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'0ab2d572-2496-11e4-8ce7-eb120a7ac5d8', NULL, E'WrongAnswer');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'420a5d74-238d-11e4-8817-7382b99f1aad', 1, 1, E'ee59a8d8-23a0-11e4-9d7f-ab33d263c791', E'Please enter a valid telephone number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'0d649a48-246f-11e4-a85c-dfb5991ff175', NULL, E'OfficePhoneValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'c78cc0b0-2232-11e4-ac12-1fd8a2b704ae', E'User Type is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'0dfb7496-2473-11e4-a771-dbb37688d074', NULL, E'UserTypeRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'75aa60a2-238d-11e4-89a0-f77e02c89a47', 1, 1, E'3401b966-23a1-11e4-a567-73d912572346', E'Account Name is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'101fbc62-2470-11e4-ac6e-bff19d4b49ee', NULL, E'AccountNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Please enter a valid email address', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'1249f46c-337a-11e4-b56f-4bb38eecda99', NULL, E'InvalidEmail');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'cb07bfc4-2232-11e4-b495-37bb7af0d6fe', E'User Status is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'12ad64cc-2473-11e4-bb29-77c5ed19dd45', NULL, E'UserStatusRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'b299a4c0-238b-11e4-bc2c-631e59d9b8c4', 1, 1, E'92f561aa-2394-11e4-aa0d-9b9e315b3eab', E'Please enter a date in specified format only dd/mm/yyyy', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'244ff81a-246a-11e4-a2ee-6fb724a70e5f', NULL, E'RenewalDateValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'82795852-2391-11e4-97a5-53fa218b5318', 1, 1, E'93c2ad3e-23b4-11e4-b3b8-0b14de35c378', E'The answer you provided does not match the answer you previously answered', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'2600b362-2496-11e4-a280-73f929d9f195', NULL, E'WrongAnswer');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'dd989bbe-239e-11e4-8ff1-c7e4f217a84b', E'Username must be at least 8 characters', NULL, False, NULL, NULL, NULL, NULL, True, False, E'27c57824-2e8f-11e4-96f8-231ebe9f7fec', NULL, E'InvalidUsernameLength');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'a2d81918-2232-11e4-b774-3b0341b43a3e', 1, 1, E'6aebf40c-2232-11e4-8bf3-63d0abf3183d', E'Please enter a full UK postcode', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'2bc443d2-2f71-11e4-a453-f349fdfd0289', NULL, E'InvalidPostCode');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'aef4cf7a-23b3-11e4-9e13-bf16b41d2b15', E'Password does not match', NULL, False, NULL, NULL, NULL, NULL, True, False, E'2ccfccfa-2e91-11e4-a251-b7516ad0ed8a', NULL, E'NoMatch');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid CLC Number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'37230f8e-3448-11e4-b59b-ab607be390de', NULL, E'CLCNumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'5e3e342a-2392-11e4-ad58-3fab4d0f9210', 1, 1, E'dd989bbe-239e-11e4-8ff1-c7e4f217a84b', E'Please enter a valid Username', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'39194712-2495-11e4-b45b-2fef2cca22bc', NULL, E'InvalidUsername');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'420a5d74-238d-11e4-8817-7382b99f1aad', 1, 1, E'ee59a8d8-23a0-11e4-9d7f-ab33d263c791', E'Telephone number cannot contain spaces', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'3b2fdf04-3447-11e4-b78b-a398418d030a', NULL, E'OfficePhoneNoSpaces');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'06c1cfaa-238c-11e4-8ed2-37d9c23496d6', 1, 1, E'19e601b0-239f-11e4-aa31-9b060ca5599f', E'Please enter a valid CRN number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'452f24a8-3445-11e4-8784-33fb457bb142', NULL, E'CRNNumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'75aa60a2-238d-11e4-89a0-f77e02c89a47', 1, 1, E'4e3e0906-23a1-11e4-98c2-577e64469c59', E'Please enter a valid sort code', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'4677c05c-2470-11e4-81c3-8f232c88f99c', NULL, E'SortCodeValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'ab0c73ba-2393-11e4-a2f7-378f82a1476d', 1, 1, E'93c2ad3e-23b4-11e4-b3b8-0b14de35c378', E'The answer you provided does not match the answer you previously answered', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'4a0a6ba4-2496-11e4-85b6-efe937f9df04', NULL, E'WrongAnswer');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6f4478a2-238c-11e4-ad79-5310f044949a', 1, 1, E'3d0ce938-239f-11e4-8c20-77181475b1a8', E'VAT registered', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'4b96ecf2-246b-11e4-bb4d-c3a8772a9f7b', NULL, E'VATRegisteredRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'a0a086de-238c-11e4-9c20-b3974ad0a7de', 1, 1, E'0761d9dc-23a0-11e4-91aa-eb94305f8cc2', E'Please enter a valid number between 1 and 9999', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'5e091ec0-246e-11e4-ac05-8bd8663f8ce0', NULL, E'NoOfCompletionsValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'4b760c88-2391-11e4-aec8-9bea036ad5a3', 1, 1, E'0773c2ea-248c-11e4-bea7-bf0bc49edde3', E'Please enter a valid email address', NULL, False, NULL, NULL, NULL, NULL, True, False, E'5f28cb96-2e8e-11e4-82c1-2f833bcb107a', NULL, E'InvalidEmail');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'93cd51ae-2232-11e4-81e3-43c7c96b4bad', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid CLC number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'5f43a538-2498-11e4-ba9c-eba86523778c', NULL, E'InvalidCLC');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'93cd51ae-2232-11e4-81e3-43c7c96b4bad', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid SRA number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'5f43a538-2498-11e4-ba9c-eba86523778c', NULL, E'InvalidSRA');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'dd989bbe-239e-11e4-8ff1-c7e4f217a84b', E'This username has already been registered in our system. Please enter a different username.', NULL, False, NULL, NULL, NULL, NULL, True, False, E'6580ee32-2e8f-11e4-bfc7-8fab1d9a3b37', NULL, E'UsernameExists');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'a0a086de-238c-11e4-9c20-b3974ad0a7de', 1, 1, E'b553a0c6-239f-11e4-99e6-b7439b268ad0', E'Please enter a valid number between 1 and 999', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'6c8175de-246d-11e4-91d4-33f7af85e118', NULL, E'NoOfRPValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'9f13d6bc-2239-11e4-9a33-0f7c434da157', 1, 1, E'a455c44a-2393-11e4-8b9d-c71eaa64022e', E'Please enter a valid website', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'6d60347a-34dc-11e4-bede-13965dd061a3', NULL, E'WebsiteValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'b299a4c0-238b-11e4-bc2c-631e59d9b8c4', 1, 1, E'1877a618-2394-11e4-8a3e-e7ebb76a4fa0', E'PII Provider is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'733cce54-2469-11e4-9083-5f3756daf9bd', NULL, E'PIIProviderRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'9d0a2d82-2232-11e4-9be4-e392814ea911', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid CLC number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'81ce17c2-2499-11e4-971c-cf22e56ab150', NULL, E'InvalidCLC');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'9d0a2d82-2232-11e4-9be4-e392814ea911', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid SRA number', NULL, False, NULL, NULL, NULL, NULL,True, False, E'81ce17c2-2499-11e4-971c-cf22e56ab150', NULL, E'InvalidSRA');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'c0ebdea8-2232-11e4-ad2d-43db229a90ed', E'Please enter a reason for rejection', NULL, False, 1901, NULL, NULL, NULL, True, False, E'83473bde-2475-11e4-83ed-574c381fe884', NULL, E'UserRejectionReasonCommentsRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid CLC number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'8683557a-2499-11e4-b612-071776c57229', NULL, E'InvalidCLC');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid SRA number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'8683557a-2499-11e4-b612-071776c57229', NULL, E'InvalidSRA');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'a0a086de-238c-11e4-9c20-b3974ad0a7de', 1, 1, E'94dc3664-239f-11e4-a411-0b54dea20d32', E'Please enter a valid number between 1 and 99', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'86a569c6-246c-11e4-af4d-83beede489a0', NULL, E'NoOfDirectorsValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password should match the below criteria', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'8722d1be-3429-11e4-85bf-2f9d714cb242', NULL, E'PasswordValidation');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'ad8fe35e-2232-11e4-a00c-1b114492e175', E'Please enter a reason for rejection', NULL, False, 1901, NULL, NULL, NULL, True, False, E'87c4a85e-2475-11e4-bb41-9bf3139a96ba', NULL, E'UserRejectionReasonRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid CLC number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'8a29acf6-2499-11e4-8d62-5f81c14a55bb', NULL, E'InvalidCLC');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid SRA number', NULL, False, NULL, NULL, NULL, NULL,True, False, E'8a29acf6-2499-11e4-8d62-5f81c14a55bb', NULL, E'InvalidSRA');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'75aa60a2-238d-11e4-89a0-f77e02c89a47', 1, 1, E'6fcb33e6-23a1-11e4-a590-5b4d1fad9964', E'Please enter a valid account number', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'8ab6a0da-2470-11e4-9fa8-6374409b2781', NULL, E'AccountNumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'29dac16e-2232-11e4-bcc5-875b01f49995', E'Title is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'94e37b54-2480-11e4-a048-3f9d7012a28b', NULL, E'TitleRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'You are about to Approve a user that we cannot validate against the SRA database. If you proceed you will be taking responsibility for the authenticity of the user. Do you wish to continue ', NULL, False, NULL, NULL, NULL, NULL, True, False, E'97656574-2483-11e4-839b-ab4dd273b576', NULL, E'ApprovingSRAFailedUser');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'2f978ec0-2232-11e4-8240-37b489a158b7', E'FirstName is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'98ee9e54-2480-11e4-8ca3-2bcf29a6bc60', NULL, E'FirstNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'29dac16e-2232-11e4-bcc5-875b01f49995', E'Title is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'9bdeea22-2473-11e4-9d47-a38b1778e80c', NULL, E'TitleRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'349b52b2-2232-11e4-b03c-b3a634177c2c', E'LastName is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'9d1f68c8-2480-11e4-9847-47ed56b62b83', NULL, E'LastNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'2f978ec0-2232-11e4-8240-37b489a158b7', E'First Name is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'9f2d8f80-2473-11e4-b940-b71256d9a221', NULL, E'FirstNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Email Address is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'a10e5034-2480-11e4-920e-07a8240ab60b', NULL, E'EmailRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'c5f6bd52-2393-11e4-96b2-9f31e5def021', E'Regulator is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'a4a33d04-2480-11e4-a148-936a01f87795', NULL, E'RegulatorRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'349b52b2-2232-11e4-b03c-b3a634177c2c', E'Last Name is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'a60876a8-2473-11e4-8f44-8b1a4ffd2799', NULL, E'LastNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'c0ebdea8-2232-11e4-ad2d-43db229a90ed', E'Please enter a reason for rejection', NULL, False, 1901, NULL, NULL, NULL,True, False, E'aa6ac64e-2232-11e4-9418-43090b174057', NULL, E'BranchRejectionReasonCommentsRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password must contain at least one special character', NULL, False, NULL, NULL, NULL, NULL, True, False, E'ac7c4b82-2e90-11e4-a433-3b37563397b3', NULL, E'MissingSpecialCharacter');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Email is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'ac9210d8-2473-11e4-9a14-6bdcf056e015', NULL, E'EmailRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'420a5d74-238d-11e4-8817-7382b99f1aad', 1, 1, E'190fa302-23a1-11e4-90a2-db87167ddd13', E'Please enter a valid telephone number', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'b3caf6b6-246f-11e4-bb80-a72b361c408d', NULL, E'DirectDialNumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'b4b5f420-2232-11e4-aab3-effe75391f5f', E'<<Existing Head Office Branch Name>> is already selected as Head Office. Do you wish to change this to <<New Head Office Branch Name>> instead?', NULL, False, NULL, NULL, NULL, NULL, True, False, E'b4b5f420-2232-11e4-aab3-effe75391f5f', NULL, E'ExistingHeadOfficeValidation');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'b4b5f420-2232-11e4-aab3-effe75391f5f', E'OfficeType is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'c3f92eac-2232-11e4-a4f1-1fc90b644a11', NULL, E'OfficeTypeRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'bb6db744-2232-11e4-b842-773e72f7c1eb', E'Branch Status is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'c78cc0b0-2232-11e4-ac12-1fd8a2b704ae', NULL, E'BranchStatusRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'ad8fe35e-2232-11e4-a00c-1b114492e175', E'Branch Rejection Reason is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'cb07bfc4-2232-11e4-b495-37bb7af0d6fe', NULL, E'BranchRejectionReasonRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password must be at least 10 characters long', NULL, False, NULL, NULL, NULL, NULL, True, False, E'cd80e410-2e8f-11e4-b703-237fd9550dd4', NULL, E'InvalidPasswordLength');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, 1, E'afca193c-2232-11e4-9b7e-c3f590179310', E'Branch Name is Required', NULL, False, 1901, NULL, NULL, NULL, True, False, E'cf242836-2232-11e4-ac66-7f6de99930b1', NULL, E'BranchNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, 1, E'119e9f3a-239f-11e4-8452-636e194b65dd', E'Password must contain at least one number', NULL, False, NULL, NULL, NULL, NULL, True, False, E'd0c0d724-2e90-11e4-9751-2f1424fc294e', NULL, E'MissingNumber');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'b299a4c0-238b-11e4-bc2c-631e59d9b8c4', 1, 1, E'4dfc601c-2394-11e4-b761-1f84f307bfd8', E'PII Policy Number is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'd26033b2-2469-11e4-a02c-bb2be6ac51fd', NULL, E'PolicyNumberRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Please enter a valid SRA Number', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'd632d520-2492-11e4-ade8-6f46f76a2704', NULL, E'SRANumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'06c1cfaa-238c-11e4-8ed2-37d9c23496d6', 1, 1, E'e1d9f18c-239e-11e4-869f-776524cf5025', E'Registered at companies house', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'd68ccec2-246a-11e4-a704-af740a016fd0', NULL, E'CompaniesHouseRegisteredRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6c3e9ede-2392-11e4-af9d-9f3708cb4b3e', 1, 1, E'afca193c-2232-11e4-9b7e-c3f590179310', E'Branch Name is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'd7b18510-2495-11e4-a074-7f0bc2d225d2', NULL, E'BranchNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6c3e9ede-2392-11e4-af9d-9f3708cb4b3e', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'Branch Regulator Number is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'dbe03f28-2495-11e4-a35a-0bfbe1063bd2', NULL, E'BranchRegulatorNumberRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, 1, E'5e67d6f6-2232-11e4-8b4b-ebd6573a5027', E'We are unable to validate the details provided against the SRA database', NULL, False, NULL, NULL, NULL, NULL,True, False, E'e8860968-2483-11e4-814c-177cd6a4b6c6', NULL, E'SRAServiceError');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'29c9159e-2391-11e4-953b-874efbbdf816', 1, 1, E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Please enter a valid Email Address', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'ea316040-2493-11e4-afce-93baa2dd8fa0', NULL, E'InvalidEmail');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'2e5f1204-223b-11e4-b7f6-0fd1c38100bb', 1, 1, E'c5f6bd52-2393-11e4-96b2-9f31e5def021', E'FirmRegulator is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'eb89cdb8-2468-11e4-81ce-9b3e66538a0f', NULL, E'FirmRegulatorRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'7f6b9150-2235-11e4-87a7-674ef85109a7', 1, 1, E'dd989bbe-239e-11e4-8ff1-c7e4f217a84b', E'Test field detail validation', NULL, False, NULL, NULL, NULL, NULL, True, False, E'ebeb7a72-2940-11e4-aded-ef924c2f89f9', NULL, E'TestValidation');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6f4478a2-238c-11e4-ad79-5310f044949a', 1, 1, E'724a220a-239f-11e4-b1c2-67caf93b9dfd', E'Please enter a valid VAT number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'f11f1672-246b-11e4-b018-f7caab769d3b', NULL, E'VATNumberValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'9f13d6bc-2239-11e4-9a33-0f7c434da157', 1, 1, E'38c4a4d0-2393-11e4-8fd0-f764af083de5', E'FirmName is required', NULL, NULL, 1901, NULL, NULL, NULL, True, False, E'fa0ce362-2467-11e4-89bd-37638f5f166b', NULL, E'FirmNameRequired');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'a0a086de-238c-11e4-9c20-b3974ad0a7de', 1, 1, E'cdd4201c-239f-11e4-9c27-7307f00ffba4', E'Please enter a valid number between 1 and 9999', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'fa9d26f6-246d-11e4-aedf-1be08cfbfc15', NULL, E'NoOfStaffValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'93cd51ae-2232-11e4-81e3-43c7c96b4bad', 1, 1, E'39c45162-2232-11e4-b67e-ef57e12c9b17', E'Please enter a valid email address', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'fd84878c-2f72-11e4-a980-a3459c999cbc', NULL, E'InvalidEmail');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'ee6f7b7e-48bf-11e4-b935-cb43a2845fba', 1, 1, E'70514602-496c-11e4-8061-0702c3031f0b', E'Please enter a valid card number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'081d2a30-4b09-11e4-865e-33c457a1c36b', NULL, E'CardNumberNotValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'ee6f7b7e-48bf-11e4-b935-cb43a2845fba', 1, 1, E'9bc78824-4948-11e4-b1a5-d38960935800', E'Please enter a valid Card Code Value', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'6cc8f0a4-4b09-11e4-b62e-f7ffcb524f57', NULL, E'CVVNotValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'f4143372-23b1-11e4-b867-7777db91cbfc', 1, 1, E'e27fc098-246c-11e4-b8a6-6b1ebb088486', E'Please enter a valid telephone number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'de403b00-4b0b-11e4-9732-efed9c413a1c', NULL, E'PhoneNotValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6dc6239c-23b2-11e4-9535-bb262a1a05f5', 1, 1, E'6fcb33e6-23a1-11e4-a590-5b4d1fad9964', E'Please enter a valid account number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'0aabe702-4b0c-11e4-9bb9-7759e79d8dc0', NULL, E'PD_AccountNumberNotValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6dc6239c-23b2-11e4-9535-bb262a1a05f5', 1, 1, E'a19952c6-246f-11e4-8b0c-63c481de2de6', E'Please enter a valid IBAN number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'4e5f9034-4b0c-11e4-8bfe-a362f72ae55d', NULL, E'IBANNotValid');

INSERT INTO public."InterfacePanelFieldDetailValidationTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "InterfacePanelFieldDetailValidationTemplateVersion", "FieldDetailTemplateID", "OverrideValidationMessage", "OverrideValidationMessageHTML", "OverrideValidationIsHTML", "ValidationType", "ValidationSubType", "ValidationCategory", "SourceErrorCodes", "IsActive", "IsDeleted", "InterfacePanelFieldDetailValidationTemplateID", "ValidationSubCategory", "InterfacePanelFieldDetailValidationTemplateName")
VALUES (E'6dc6239c-23b2-11e4-9535-bb262a1a05f5', 1, 1, E'bb50efee-246f-11e4-9c38-7f2086e22c21', E'Please enter a valid SWIFT/BIC number', NULL, NULL, NULL, NULL, NULL, NULL, True, False, E'93d87b80-4b0c-11e4-87fa-b3f8a43d755a', NULL, E'SWIFTNotValid');