/* Data for the 'public.InterfacePanelTemplate' table  (Records 1 - 61) */

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'04401532-2488-11e4-817a-d7c07e984cd7', 1, E'InternationalAddress', NULL, NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'29c9159e-2391-11e4-953b-874efbbdf816', 1, E'ForgotUsername', E'Forgot username', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'3288ba52-2488-11e4-b670-fb3a5a55fe0f', 1, E'BranchesUsersSetUp', E'BranchesUsersSetUp', NULL, NULL, NULL, NULL, True, False, NULL, NULL, True, False, True, E'Setup Branches');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, E'Payments', E'Payments', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Payment');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'5cc14b72-2393-11e4-8e99-1773c703c71a', 1, E'ChangeUserPassword', E'User changing password screen', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'759a0024-2237-11e4-b86b-db81260b98c5', 1, E'FirmDetailsUser', E'User Firm Details', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Firm Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'7f6b9150-2235-11e4-87a7-674ef85109a7', 1, E'Login', E'Login', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Login');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'8fc171da-23d1-11e4-80f8-d30fc8c965a8', 1, E'FirmTradingName', E'Additional Trading Names', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Additional Trading Names');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'98b2d736-3a59-11e4-af52-3345c5dc7cc3', 1, E'PreviousAddress', E'PreviousAddress', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'My previous addresses:');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, E'Register', E'Register', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, E'ForgotPassword', E'Forgot password', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a2d81918-2232-11e4-b774-3b0341b43a3e', 1, E'Address', E'Address', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a6298fd6-23b1-11e4-862d-3f42f647fe18', 1, E'PersonalDetails', NULL, NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a76467f8-2236-11e4-a090-2b2b425d524b', 1, E'CreateLogin', E'Create login', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, E'FirmDetailsUser', E'User Firm Details', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Firm Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, E'RegistrationSummary', E'Registration Summary for COLP', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Registration Summary');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'b82e3666-3a5c-11e4-845c-0fa0fcd6ea34', 1, E'UserManagement', E'UserManagement', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'User Management');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'bb6db744-2232-11e4-b842-773e72f7c1eb', 1, E'AddUser', E'Add User', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'User Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'c96749b0-4a22-11e4-bf5e-63293b45dbd6', 1, E'ProductDescription', E'Product Desciption on payment', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, NULL);

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, E'FirmDetailsCOLP', E'COLP Firm Details ', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Firm Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'd4a49390-2232-11e4-9add-2f7a2a2ee654', 1, E'AddBranch', E'Add Branch', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Approve Branch');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'e3b38f24-248c-11e4-a7ed-dbf7306b6c1d', 1, E'NextSteps', E'Next Steps', NULL, NULL, NULL, NULL, True, False, NULL, NULL, False, False, True, E'Next Steps');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'4b760c88-2391-11e4-aec8-9bea036ad5a3', 1, E'ForgottenUsername', E'Forgotten username', NULL, NULL, NULL, NULL, True, False, E'29c9159e-2391-11e4-953b-874efbbdf816', 1, False, False, True, E'Forgotten Username');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'82795852-2391-11e4-97a5-53fa218b5318', 1, E'ForgotUsernameSecurityQuestion', E'User has to answer security question when forgotten username', NULL, NULL, NULL, NULL, True, False, E'29c9159e-2391-11e4-953b-874efbbdf816', 1, False, False, True, E'Please answer your security question below:');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'3ae9bf2a-2488-11e4-8ee1-2f469d9c920f', 1, E'Branches', E'Branches', NULL, NULL, NULL, NULL, True, False, E'3288ba52-2488-11e4-b670-fb3a5a55fe0f', 1, True, True, False, E'Branches');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'4546da8e-2488-11e4-a1d7-7fd56ca787b9', 1, E'Users', E'Users', NULL, NULL, NULL, NULL, True, False, E'3288ba52-2488-11e4-b670-fb3a5a55fe0f', 1, True, True, False, E'Users');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'3274e0f2-48c0-11e4-ba88-a3a20b7ea166', 1, E'OrderSummary', E'Payment Order Summary', NULL, NULL, NULL, NULL, True, False, E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, False, False, True, E'Your Order Summary');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'ee6f7b7e-48bf-11e4-b935-cb43a2845fba', 1, E'PaymentDetails', E'Payment Details', NULL, NULL, NULL, NULL, True, False, E'3e9c3fae-26b2-11e4-9a24-b32951fa39f8', 1, False, False, True, E'Payment Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'ab0c73ba-2393-11e4-a2f7-378f82a1476d', 1, E'ChangePassword', E'Change password', NULL, NULL, NULL, NULL, True, False, E'5cc14b72-2393-11e4-8e99-1773c703c71a', 1, False, False, True, E'Change Password');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'e9518b1a-2393-11e4-93af-47ec99dc63ef', 1, E'SecurityQuestion', E'Security question', NULL, NULL, NULL, NULL, True, False, E'5cc14b72-2393-11e4-8e99-1773c703c71a', 1, False, False, True, E'Security Question');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'93cd51ae-2232-11e4-81e3-43c7c96b4bad', 1, E'RegisterCODetails', E'RegisterCODetails', NULL, NULL, NULL, NULL, True, False, E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, False, False, True, E'Compliance Officer’s Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'96d3c7d4-2232-11e4-a25c-4be0f8e22925', 1, E'RegisterMyDetails', E'RegisterMyDetails', NULL, NULL, NULL, NULL, True, False, E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, False, False, True, E'My Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'99450b5e-2232-11e4-aa4d-7f9f51bc2f7f', 1, E'RegisterFirmDetails', E'RegisterFirmDetails', NULL, NULL, NULL, NULL, True, False, E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, False, False, True, E'Firm Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'9d0a2d82-2232-11e4-9be4-e392814ea911', 1, E'RegisterCOOfficeDetails', E'RegisterCOOfficeDetails', NULL, NULL, NULL, NULL, True, False, E'9fdcece8-2232-11e4-bf45-ab038058bfc9', 1, False, False, True, E'Compliance Officer’s Office Address');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'1835a336-2393-11e4-baba-93eb4d1c6be6', 1, E'ForgotPasswordSecurityQuestion', E'Forgot password security question', NULL, NULL, NULL, NULL, True, False, E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, False, False, True, E'Please answer your security question below:');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'5e3e342a-2392-11e4-ad58-3fab4d0f9210', 1, E'ForgottenPassword', E'Forgotten password', NULL, NULL, NULL, NULL, True, False, E'a1637288-2392-11e4-a556-cb3839eec9ed', 1, False, False, True, E'Forgotten Password');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'6dc6239c-23b2-11e4-9535-bb262a1a05f5', 1, E'ID+', E'ID+', NULL, NULL, NULL, NULL, True, False, E'a6298fd6-23b1-11e4-862d-3f42f647fe18', 1, False, False, True, E'ID+');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'f4143372-23b1-11e4-b867-7777db91cbfc', 1, E'PersonalDetailsPanel', E'Personal details', NULL, NULL, NULL, NULL, True, False, E'a6298fd6-23b1-11e4-862d-3f42f647fe18', 1, False, False, True, E'Personal Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'8c894ee8-2390-11e4-8d91-9fcf5019eafd', 1, E'CreateYourLogins', E'Create your logins', NULL, NULL, NULL, NULL, True, False, E'a76467f8-2236-11e4-a090-2b2b425d524b', 1, False, False, True, E'Create your logins');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'b447bc3a-2390-11e4-8dc1-07b1b34177be', 1, E'SecurityQuestions', E'Security questions', NULL, NULL, NULL, NULL, True, False, E'a76467f8-2236-11e4-a090-2b2b425d524b', 1, False, False, True, E'Security Questions');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'02d28498-2391-11e4-a59c-67464c577986', 1, E'COLPDetails', E'Compliance Officer Details', NULL, NULL, NULL, NULL, True, False, E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, False, False, True, E'Compliance Officers Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'5d014074-4878-11e4-8a7b-5f664f075a9f', 1, E'UserFirmRegulator', E'UserFirmRegulator', NULL, NULL, NULL, NULL, True, False, E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, False, False, True, E'Firm''s Regulator');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'6c3e9ede-2392-11e4-af9d-9f3708cb4b3e', 1, E'Branch', E'Branch', NULL, NULL, NULL, NULL, True, False, E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, False, False, True, E'Branch Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'904495b2-4878-11e4-86b7-7b05b54dee9c', 1, E'UserFirmContact', E'UserFirmContact', NULL, NULL, NULL, NULL, True, False, E'a81fa4f4-2390-11e4-b07e-2300506dc125', 1, False, False, True, E'Firm Contact Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'58a83c72-47c3-11e4-b842-a382b0b84eb9', 1, E'Firm', E'Firm Name', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Firm');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'5a096634-47bb-11e4-9034-9754a544bb20', 1, E'RegistrationSummaryFirmOptions', E'Firm Option for Registration Summary', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Firm Options');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'9047425c-47bb-11e4-8f34-372708deb2c1', 1, E'YourProducts', E'Your Products on Registration Summary', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Your Products');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'974067d4-47c3-11e4-a413-878d2332f1d8', 1, E'HeadOffice', E'Head Office Address', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Head Office');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'f1ac1c68-47c3-11e4-9cd7-dfbd5144664c', 1, E'Myself', E'COLP Name', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Myself');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'fe6c1f1a-47ba-11e4-b16b-83185efa7136', 1, E'RegistrationSummaryBranchesAndUsers', E'Branches and Users on Registration Summary', NULL, NULL, NULL, NULL, True, False, E'b0a98160-47b9-11e4-b69c-33bda23a3ae7', 1, False, False, True, E'Branches and Users');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'0201e42c-47f5-11e4-bf56-f7b72de32dfe', 1, E'Memberships', E'Memberships', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Memberships');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'06c1cfaa-238c-11e4-8ed2-37d9c23496d6', 1, E'FirmRegistration', E'Firm Registration', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Firm Registration');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'0a0ad3b2-3450-11e4-8983-b327ad169744', 1, E'FirmCOForFinanceAndAdministration', E'Compliance Officer for Finance and Administration', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Compliance Officer for Finance and Administration');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'2e5f1204-223b-11e4-b7f6-0fd1c38100bb', 1, E'FirmRegulator', E'Firm Regulator', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Firm''s Regulator');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'420a5d74-238d-11e4-8817-7382b99f1aad', 1, E'ContactDetails', E'Contact Details', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Contact Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'6f4478a2-238c-11e4-ad79-5310f044949a', 1, E'FirmVATDetails', E'VAT Details', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'VAT Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'75aa60a2-238d-11e4-89a0-f77e02c89a47', 1, E'FirmClientAccountDetails', E'Client Account Details', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Client Account Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'9f13d6bc-2239-11e4-9a33-0f7c434da157', 1, E'FirmContact', E'Firm Contact Details', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Firm Contact Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'a0a086de-238c-11e4-9c20-b3974ad0a7de', 1, E'FirmOtherDetails', E'Other Details', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Other Details');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'b299a4c0-238b-11e4-bc2c-631e59d9b8c4', 1, E'FirmProfessionalIndemnityInsurance', E'Professional Indemnity Insurance', NULL, NULL, NULL, NULL, True, False, E'cedd61ae-2236-11e4-b7d7-73e6f5407cab', 1, False, False, True, E'Professional Indemnity Insurance (PII)');

INSERT INTO public."InterfacePanelTemplate" ("InterfacePanelTemplateID", "InterfacePanelTemplateVersionNumber", "Name", "Description", "InterfacePanelTypeID", "InterfacePanelSubTypeID", "InterfacePanelCategoryID", "InterfacePanelSubCategoryID", "IsActive", "IsDeleted", "ParentIPTemplateID", "ParentIPTemplateVersionNumber", "IsSecuredByClaim", "IsGridPanel", "IsGlobal", "InterfacePanelTemplateLabel")
VALUES (E'4ee1a43e-248d-11e4-a34c-63508806289d', 1, E'BeforeYouRegister', E'Before You Register', NULL, NULL, NULL, NULL, True, False, E'e3b38f24-248c-11e4-a7ed-dbf7306b6c1d', 1, False, False, True, E'Before You Register');