//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 2/5/2015 2:37:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data.Analysis
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.Analysis.AnalysisBatchProcessor in the schema.
    /// </summary>
    public partial class AnalysisBatchProcessor    {

        public AnalysisBatchProcessor()
        {
          this.AnalysisBatchProcessorVersionNumber = 0;
          this.IsActive = true;
          this.IsDeleted = false;
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for AnalysisBatchProcessorID in the schema.
        /// </summary>
        public virtual global::System.Guid AnalysisBatchProcessorID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnalysisBatchProcessorVersionNumber in the schema.
        /// </summary>
        public virtual int AnalysisBatchProcessorVersionNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        public virtual bool IsActive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        public virtual bool IsDeleted
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnalysisBatchProcessorTypeID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> AnalysisBatchProcessorTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnalysisBatchProcessorCategoryID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> AnalysisBatchProcessorCategoryID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ObjectName in the schema.
        /// </summary>
        public virtual string ObjectName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ObjectAssembly in the schema.
        /// </summary>
        public virtual string ObjectAssembly
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for AnalysisInterfaces in the schema.
        /// </summary>
        public virtual ICollection<AnalysisInterface> AnalysisInterfaces
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
