//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 24/03/2015 09:58:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data.Analysis
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.Analysis.AnalysisInputMortgageApplicationDetail in the schema.
    /// </summary>
    public partial class AnalysisInputMortgageApplicationDetail    {

        public AnalysisInputMortgageApplicationDetail()
        {
          this.IsActive = true;
          this.IsDeleted = false;
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for AnalysisInputMortgageApplicationDetailID in the schema.
        /// </summary>
        public virtual global::System.Guid AnalysisInputMortgageApplicationDetailID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AnalysisInputMortgageApplicationID in the schema.
        /// </summary>
        public virtual global::System.Guid AnalysisInputMortgageApplicationID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SearchReferenceKey in the schema.
        /// </summary>
        public virtual string SearchReferenceKey
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Lender in the schema.
        /// </summary>
        public virtual string Lender
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Domain in the schema.
        /// </summary>
        public virtual string Domain
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MortgageApplicationNumber in the schema.
        /// </summary>
        public virtual string MortgageApplicationNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        public virtual bool IsActive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        public virtual bool IsDeleted
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for AnalysisInputMortgageApplication in the schema.
        /// </summary>
        public virtual AnalysisInputMortgageApplication AnalysisInputMortgageApplication
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
