//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07/04/2015 09:00:39
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace TargetFrameworkCoreModel
{

    /// <summary>
    /// There are no comments for TargetFrameworkCoreModel.ClassificationTypeCategory in the schema.
    /// </summary>
    public partial class ClassificationTypeCategory    {

        public ClassificationTypeCategory()
        {
          this.IsActive = true;
          this.IsDeleted = false;
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for ClassificationTypeCategoryID in the schema.
        /// </summary>
        public virtual int ClassificationTypeCategoryID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        public virtual bool IsActive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        public virtual bool IsDeleted
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for ClassificationTypes_ParentClassificationTypeCategoryID in the schema.
        /// </summary>
        public virtual ICollection<ClassificationType> ClassificationTypes_ParentClassificationTypeCategoryID
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for ClassificationTypes_ClassificationTypeCategoryID in the schema.
        /// </summary>
        public virtual ICollection<ClassificationType> ClassificationTypes_ClassificationTypeCategoryID
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
