//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 08/06/2015 16:32:47
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.SB.Data
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.SB.Data.BusMessage in the schema.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [System.Runtime.Serialization.KnownType(typeof(BusMessageProcessLog))]
    [System.Runtime.Serialization.KnownType(typeof(BusMessageContent))]
    public partial class BusMessage    {

        public BusMessage()
        {
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for MessageId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Guid MessageId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CorrelationId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Guid CorrelationId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BusMessageID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Guid BusMessageID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ConversationId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Guid ConversationId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for SentOn in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<System.DateTime> SentOn
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EnclosedMessageTypes in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string EnclosedMessageTypes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for WinIdName in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string WinIdName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProcessingMachine in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string ProcessingMachine
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ProcessingStarted in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<System.DateTime> ProcessingStarted
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for BusMessageTypeID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual int BusMessageTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MessageSentFrom in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string MessageSentFrom
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Source in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Source
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ParentID in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<System.Guid> ParentID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EventReference in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string EventReference
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedOn in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.DateTime CreatedOn
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string CreatedBy
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for BusMessageProcessLogs in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual ICollection<BusMessageProcessLog> BusMessageProcessLogs
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for BusMessageContents in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual ICollection<BusMessageContent> BusMessageContents
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
