//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 17/04/2015 16:46:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class ApplicationStageDTO
    {
        #region Constructors
  
        public ApplicationStageDTO() {
        }

        public ApplicationStageDTO(global::System.Guid applicationStageID, string name, string description, int order, bool isActive, bool isDeleted, List<ApplicationStageWorkflowDTO> applicationStageWorkflows) {

          this.ApplicationStageID = applicationStageID;
          this.Name = name;
          this.Description = description;
          this.Order = order;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.ApplicationStageWorkflows = applicationStageWorkflows;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid ApplicationStageID { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public int Order { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<ApplicationStageWorkflowDTO> ApplicationStageWorkflows { get; set; }

        #endregion
    }

}
