//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 17/04/2015 16:46:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class BillingTemplateDTO
    {
        #region Constructors
  
        public BillingTemplateDTO() {
        }

        public BillingTemplateDTO(global::System.Guid billingTemplateID, int billingPeriod, int billingPeriodUnitID, global::System.Nullable<int> billingPeriodDayOfMonth, global::System.Nullable<int> delayedBillingPeriod, global::System.Nullable<int> delayedBillingPeriodUnitID, global::System.Nullable<bool> hasDelayedBilling, global::System.Nullable<int> numberOfBillingPeriods, global::System.Nullable<int> invoiceToProcessingDelayPeriod, global::System.Nullable<int> invoiceToProcessingDelayPeriodUnitID, global::System.Nullable<System.Guid> invoiceNotificationConstructTemplateID, global::System.Nullable<int> invoiceNotificationConstructTemplateVersionNumber, global::System.Nullable<int> estimatedProcessingPeriod, global::System.Nullable<int> estimatedProcessingPeriodUnitID, bool isActive, bool isDeleted, global::System.Nullable<System.Guid> parentID, global::System.Nullable<int> billingLagPeriod, global::System.Nullable<int> billingLagPeriodUnitID, List<PlanBillingTemplateDTO> planBillingTemplates, List<PlanGlobalPaymentMethodTemplateDTO> planGlobalPaymentMethodTemplates, List<BillingDTO> billings) {

          this.BillingTemplateID = billingTemplateID;
          this.BillingPeriod = billingPeriod;
          this.BillingPeriodUnitID = billingPeriodUnitID;
          this.BillingPeriodDayOfMonth = billingPeriodDayOfMonth;
          this.DelayedBillingPeriod = delayedBillingPeriod;
          this.DelayedBillingPeriodUnitID = delayedBillingPeriodUnitID;
          this.HasDelayedBilling = hasDelayedBilling;
          this.NumberOfBillingPeriods = numberOfBillingPeriods;
          this.InvoiceToProcessingDelayPeriod = invoiceToProcessingDelayPeriod;
          this.InvoiceToProcessingDelayPeriodUnitID = invoiceToProcessingDelayPeriodUnitID;
          this.InvoiceNotificationConstructTemplateID = invoiceNotificationConstructTemplateID;
          this.InvoiceNotificationConstructTemplateVersionNumber = invoiceNotificationConstructTemplateVersionNumber;
          this.EstimatedProcessingPeriod = estimatedProcessingPeriod;
          this.EstimatedProcessingPeriodUnitID = estimatedProcessingPeriodUnitID;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.ParentID = parentID;
          this.BillingLagPeriod = billingLagPeriod;
          this.BillingLagPeriodUnitID = billingLagPeriodUnitID;
          this.PlanBillingTemplates = planBillingTemplates;
          this.PlanGlobalPaymentMethodTemplates = planGlobalPaymentMethodTemplates;
          this.Billings = billings;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid BillingTemplateID { get; set; }

        [DataMember]
        public int BillingPeriod { get; set; }

        [DataMember]
        public int BillingPeriodUnitID { get; set; }

        [DataMember]
        public global::System.Nullable<int> BillingPeriodDayOfMonth { get; set; }

        [DataMember]
        public global::System.Nullable<int> DelayedBillingPeriod { get; set; }

        [DataMember]
        public global::System.Nullable<int> DelayedBillingPeriodUnitID { get; set; }

        [DataMember]
        public global::System.Nullable<bool> HasDelayedBilling { get; set; }

        [DataMember]
        public global::System.Nullable<int> NumberOfBillingPeriods { get; set; }

        [DataMember]
        public global::System.Nullable<int> InvoiceToProcessingDelayPeriod { get; set; }

        [DataMember]
        public global::System.Nullable<int> InvoiceToProcessingDelayPeriodUnitID { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> InvoiceNotificationConstructTemplateID { get; set; }

        [DataMember]
        public global::System.Nullable<int> InvoiceNotificationConstructTemplateVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<int> EstimatedProcessingPeriod { get; set; }

        [DataMember]
        public global::System.Nullable<int> EstimatedProcessingPeriodUnitID { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> ParentID { get; set; }

        [DataMember]
        public global::System.Nullable<int> BillingLagPeriod { get; set; }

        [DataMember]
        public global::System.Nullable<int> BillingLagPeriodUnitID { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<PlanBillingTemplateDTO> PlanBillingTemplates { get; set; }

        [DataMember]
        public List<PlanGlobalPaymentMethodTemplateDTO> PlanGlobalPaymentMethodTemplates { get; set; }

        [DataMember]
        public List<BillingDTO> Billings { get; set; }

        #endregion
    }

}
