//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class HelpItemDTO
    {
        #region Constructors
  
        public HelpItemDTO() {
        }

        public HelpItemDTO(global::System.Guid helpItemID, global::System.Guid helpPageID, string title, string description, int displayOrder, string selector, string tabContainerId, global::System.Nullable<System.DateTime> effectiveOn, global::System.Nullable<int> position, global::System.DateTime createdOn, global::System.Nullable<System.DateTime> modifiedOn, string createdBy, string modifiedBy, HelpPageDTO helpPage, List<HelpItemUserAccountDTO> helpItemUserAccounts) {

          this.HelpItemID = helpItemID;
          this.HelpPageID = helpPageID;
          this.Title = title;
          this.Description = description;
          this.DisplayOrder = displayOrder;
          this.Selector = selector;
          this.TabContainerId = tabContainerId;
          this.EffectiveOn = effectiveOn;
          this.Position = position;
          this.CreatedOn = createdOn;
          this.ModifiedOn = modifiedOn;
          this.CreatedBy = createdBy;
          this.ModifiedBy = modifiedBy;
          this.HelpPage = helpPage;
          this.HelpItemUserAccounts = helpItemUserAccounts;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid HelpItemID { get; set; }

        [DataMember]
        public global::System.Guid HelpPageID { get; set; }

        [DataMember]
        public string Title { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public int DisplayOrder { get; set; }

        [DataMember]
        public string Selector { get; set; }

        [DataMember]
        public string TabContainerId { get; set; }

        [DataMember]
        public global::System.Nullable<System.DateTime> EffectiveOn { get; set; }

        [DataMember]
        public global::System.Nullable<int> Position { get; set; }

        [DataMember]
        public global::System.DateTime CreatedOn { get; set; }

        [DataMember]
        public global::System.Nullable<System.DateTime> ModifiedOn { get; set; }

        [DataMember]
        public string CreatedBy { get; set; }

        [DataMember]
        public string ModifiedBy { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public HelpPageDTO HelpPage { get; set; }

        [DataMember]
        public List<HelpItemUserAccountDTO> HelpItemUserAccounts { get; set; }

        #endregion
    }

}
