//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 6/27/2014 3:05:11 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    public partial class ModuleWorkflowUserStageDTO
    {
        #region Constructors
  
        public ModuleWorkflowUserStageDTO() {
        }

        public ModuleWorkflowUserStageDTO(global::System.Guid moduleWorkflowUserStageID, global::System.Guid userStageTemplateID, global::System.Guid moduleWorkflowID, global::System.Nullable<int> userTypeID, global::System.Nullable<int> userSubTypeID, global::System.Nullable<int> userCategoryID, global::System.Nullable<int> userSubCategoryID, bool appliesToAllUsers, ModuleWorkflowDTO moduleWorkflow, UserStageTemplateDTO userStageTemplate) {

          this.ModuleWorkflowUserStageID = moduleWorkflowUserStageID;
          this.UserStageTemplateID = userStageTemplateID;
          this.ModuleWorkflowID = moduleWorkflowID;
          this.UserTypeID = userTypeID;
          this.UserSubTypeID = userSubTypeID;
          this.UserCategoryID = userCategoryID;
          this.UserSubCategoryID = userSubCategoryID;
          this.AppliesToAllUsers = appliesToAllUsers;
          this.ModuleWorkflow = moduleWorkflow;
          this.UserStageTemplate = userStageTemplate;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid ModuleWorkflowUserStageID { get; set; }

        [DataMember]
        public global::System.Guid UserStageTemplateID { get; set; }

        [DataMember]
        public global::System.Guid ModuleWorkflowID { get; set; }

        [DataMember]
        public global::System.Nullable<int> UserTypeID { get; set; }

        [DataMember]
        public global::System.Nullable<int> UserSubTypeID { get; set; }

        [DataMember]
        public global::System.Nullable<int> UserCategoryID { get; set; }

        [DataMember]
        public global::System.Nullable<int> UserSubCategoryID { get; set; }

        [DataMember]
        public bool AppliesToAllUsers { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public ModuleWorkflowDTO ModuleWorkflow { get; set; }

        [DataMember]
        public UserStageTemplateDTO UserStageTemplate { get; set; }

        #endregion
    }

}
