//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class NotificationConstructGroupNotificationConstructTemplateDTO
    {
        #region Constructors
  
        public NotificationConstructGroupNotificationConstructTemplateDTO() {
        }

        public NotificationConstructGroupNotificationConstructTemplateDTO(global::System.Guid notificationConstructGroupNotificationConstructTemplateID, int notificationConstructGroupNotificationConstructTemplateVersion, global::System.Nullable<System.Guid> notificationConstructGroupTemplateID, global::System.Nullable<int> notificationConstructGroupTemplateVersion, global::System.Nullable<System.Guid> userTypeID, global::System.Guid notificationConstructTemplateID, global::System.Nullable<System.Guid> workflowTemplateID, global::System.Nullable<int> workflowTemplateVersionNumber, global::System.Nullable<bool> isActive, global::System.Nullable<bool> isDeleted, string conditionString, int notificationConstructTemplateVersionNumber, global::System.Nullable<int> organisationTypeID, NotificationConstructGroupTemplateDTO notificationConstructGroupTemplate, WorkflowTemplateDTO workflowTemplate, UserTypeDTO userType, OrganisationTypeDTO organisationType, NotificationConstructTemplateDTO notificationConstructTemplate) {

          this.NotificationConstructGroupNotificationConstructTemplateID = notificationConstructGroupNotificationConstructTemplateID;
          this.NotificationConstructGroupNotificationConstructTemplateVersion = notificationConstructGroupNotificationConstructTemplateVersion;
          this.NotificationConstructGroupTemplateID = notificationConstructGroupTemplateID;
          this.NotificationConstructGroupTemplateVersion = notificationConstructGroupTemplateVersion;
          this.UserTypeID = userTypeID;
          this.NotificationConstructTemplateID = notificationConstructTemplateID;
          this.WorkflowTemplateID = workflowTemplateID;
          this.WorkflowTemplateVersionNumber = workflowTemplateVersionNumber;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.ConditionString = conditionString;
          this.NotificationConstructTemplateVersionNumber = notificationConstructTemplateVersionNumber;
          this.OrganisationTypeID = organisationTypeID;
          this.NotificationConstructGroupTemplate = notificationConstructGroupTemplate;
          this.WorkflowTemplate = workflowTemplate;
          this.UserType = userType;
          this.OrganisationType = organisationType;
          this.NotificationConstructTemplate = notificationConstructTemplate;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid NotificationConstructGroupNotificationConstructTemplateID { get; set; }

        [DataMember]
        public int NotificationConstructGroupNotificationConstructTemplateVersion { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> NotificationConstructGroupTemplateID { get; set; }

        [DataMember]
        public global::System.Nullable<int> NotificationConstructGroupTemplateVersion { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> UserTypeID { get; set; }

        [DataMember]
        public global::System.Guid NotificationConstructTemplateID { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> WorkflowTemplateID { get; set; }

        [DataMember]
        public global::System.Nullable<int> WorkflowTemplateVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<bool> IsActive { get; set; }

        [DataMember]
        public global::System.Nullable<bool> IsDeleted { get; set; }

        [DataMember]
        public string ConditionString { get; set; }

        [DataMember]
        public int NotificationConstructTemplateVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<int> OrganisationTypeID { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public NotificationConstructGroupTemplateDTO NotificationConstructGroupTemplate { get; set; }

        [DataMember]
        public WorkflowTemplateDTO WorkflowTemplate { get; set; }

        [DataMember]
        public UserTypeDTO UserType { get; set; }

        [DataMember]
        public OrganisationTypeDTO OrganisationType { get; set; }

        [DataMember]
        public NotificationConstructTemplateDTO NotificationConstructTemplate { get; set; }

        #endregion
    }

}
