//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 18/03/2015 19:00:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class NotificationConstructTargetTemplateDTO
    {
        #region Constructors
  
        public NotificationConstructTargetTemplateDTO() {
        }

        public NotificationConstructTargetTemplateDTO(global::System.Guid notificationConstructTargetTemplateID, global::System.Guid notificationConstructTemplateID, int notificationConstructTemplateVersionNumber, global::System.Nullable<int> organisationTypeID, global::System.Nullable<System.Guid> userTypeID, bool isSingleUser, bool isOrganisationBranchOnly, bool isDefaultTarget, bool isActive, bool isDeleted, NotificationConstructTemplateDTO notificationConstructTemplate, OrganisationTypeDTO organisationType, UserTypeDTO userType) {

          this.NotificationConstructTargetTemplateID = notificationConstructTargetTemplateID;
          this.NotificationConstructTemplateID = notificationConstructTemplateID;
          this.NotificationConstructTemplateVersionNumber = notificationConstructTemplateVersionNumber;
          this.OrganisationTypeID = organisationTypeID;
          this.UserTypeID = userTypeID;
          this.IsSingleUser = isSingleUser;
          this.IsOrganisationBranchOnly = isOrganisationBranchOnly;
          this.IsDefaultTarget = isDefaultTarget;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.NotificationConstructTemplate = notificationConstructTemplate;
          this.OrganisationType = organisationType;
          this.UserType = userType;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid NotificationConstructTargetTemplateID { get; set; }

        [DataMember]
        public global::System.Guid NotificationConstructTemplateID { get; set; }

        [DataMember]
        public int NotificationConstructTemplateVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<int> OrganisationTypeID { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> UserTypeID { get; set; }

        [DataMember]
        public bool IsSingleUser { get; set; }

        [DataMember]
        public bool IsOrganisationBranchOnly { get; set; }

        [DataMember]
        public bool IsDefaultTarget { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public NotificationConstructTemplateDTO NotificationConstructTemplate { get; set; }

        [DataMember]
        public OrganisationTypeDTO OrganisationType { get; set; }

        [DataMember]
        public UserTypeDTO UserType { get; set; }

        #endregion
    }

}
