//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 6/10/2014 2:36:07 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities.DTO
{

    [DataContractAttribute(IsReference=true)]
    public partial class OrganisationGroupOrganisationRoleDTO
    {
        #region Constructors
  
        public OrganisationGroupOrganisationRoleDTO() {
        }

        public OrganisationGroupOrganisationRoleDTO(global::System.Guid organisationGroupID, global::System.Guid organisationRoleID, bool isActive, bool isDeleted) {

          this.OrganisationGroupID = organisationGroupID;
          this.OrganisationRoleID = organisationRoleID;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid OrganisationGroupID { get; set; }

        [DataMember]
        public global::System.Guid OrganisationRoleID { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion
    }

}
