//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 2/12/2015 3:31:07 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class OrganisationShoppingCartBlueprintDTO
    {
        #region Constructors
  
        public OrganisationShoppingCartBlueprintDTO() {
        }

        public OrganisationShoppingCartBlueprintDTO(global::System.Nullable<System.Guid> organisationID, global::System.Nullable<System.Guid> shoppingCartBlueprintID, bool isActive, bool isDeleted, OrganisationDTO organisation, ShoppingCartBlueprintDTO shoppingCartBlueprint) {

          this.OrganisationID = organisationID;
          this.ShoppingCartBlueprintID = shoppingCartBlueprintID;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.Organisation = organisation;
          this.ShoppingCartBlueprint = shoppingCartBlueprint;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Nullable<System.Guid> OrganisationID { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> ShoppingCartBlueprintID { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public OrganisationDTO Organisation { get; set; }

        [DataMember]
        public ShoppingCartBlueprintDTO ShoppingCartBlueprint { get; set; }

        #endregion
    }

}
