//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 02/04/2015 16:41:50
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class SpecificationAttributeOptionTemplateDTO
    {
        #region Constructors
  
        public SpecificationAttributeOptionTemplateDTO() {
        }

        public SpecificationAttributeOptionTemplateDTO(global::System.Guid specificationAttributeOptionTemplateID, global::System.Guid specificationAttributeTemplateID, string name, string description, bool isActive, bool isDeleted, int displayOrder, int order, List<ProductSpecificationAttributeOptionTemplateDTO> productSpecificationAttributeOptionTemplates, SpecificationAttributeTemplateDTO specificationAttributeTemplate) {

          this.SpecificationAttributeOptionTemplateID = specificationAttributeOptionTemplateID;
          this.SpecificationAttributeTemplateID = specificationAttributeTemplateID;
          this.Name = name;
          this.Description = description;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.DisplayOrder = displayOrder;
          this.Order = order;
          this.ProductSpecificationAttributeOptionTemplates = productSpecificationAttributeOptionTemplates;
          this.SpecificationAttributeTemplate = specificationAttributeTemplate;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid SpecificationAttributeOptionTemplateID { get; set; }

        [DataMember]
        public global::System.Guid SpecificationAttributeTemplateID { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public int DisplayOrder { get; set; }

        [DataMember]
        public int Order { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<ProductSpecificationAttributeOptionTemplateDTO> ProductSpecificationAttributeOptionTemplates { get; set; }

        [DataMember]
        public SpecificationAttributeTemplateDTO SpecificationAttributeTemplate { get; set; }

        #endregion
    }

}
