//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 2/12/2015 3:31:07 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class StsSearchPropertyDTO
    {
        #region Constructors
  
        public StsSearchPropertyDTO() {
        }

        public StsSearchPropertyDTO(global::System.Guid stsSearchID, global::System.Guid stsPropertyID, decimal propertyPrice, global::System.Nullable<int> propertyTenureID, global::System.Nullable<int> propertySellerRelationshipTypeID, global::System.Guid stsSearchPropertyID, StsPropertyDTO stsProperty, StsSearchDTO stsSearch, List<LRTitleDTO> lRTitles) {

          this.StsSearchID = stsSearchID;
          this.StsPropertyID = stsPropertyID;
          this.PropertyPrice = propertyPrice;
          this.PropertyTenureID = propertyTenureID;
          this.PropertySellerRelationshipTypeID = propertySellerRelationshipTypeID;
          this.StsSearchPropertyID = stsSearchPropertyID;
          this.StsProperty = stsProperty;
          this.StsSearch = stsSearch;
          this.LRTitles = lRTitles;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid StsSearchID { get; set; }

        [DataMember]
        public global::System.Guid StsPropertyID { get; set; }

        [DataMember]
        public decimal PropertyPrice { get; set; }

        [DataMember]
        public global::System.Nullable<int> PropertyTenureID { get; set; }

        [DataMember]
        public global::System.Nullable<int> PropertySellerRelationshipTypeID { get; set; }

        [DataMember]
        public global::System.Guid StsSearchPropertyID { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public StsPropertyDTO StsProperty { get; set; }

        [DataMember]
        public StsSearchDTO StsSearch { get; set; }

        [DataMember]
        public List<LRTitleDTO> LRTitles { get; set; }

        #endregion
    }

}
