//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class UserAccountOrganisationFunctionDTO
    {
        #region Constructors
  
        public UserAccountOrganisationFunctionDTO() {
        }

        public UserAccountOrganisationFunctionDTO(global::System.Guid userAccountOrganisationID, global::System.Guid functionID, bool isActive, bool isDeleted, UserAccountOrganisationDTO userAccountOrganisation, FunctionDTO function) {

          this.UserAccountOrganisationID = userAccountOrganisationID;
          this.FunctionID = functionID;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.UserAccountOrganisation = userAccountOrganisation;
          this.Function = function;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid UserAccountOrganisationID { get; set; }

        [DataMember]
        public global::System.Guid FunctionID { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public UserAccountOrganisationDTO UserAccountOrganisation { get; set; }

        [DataMember]
        public FunctionDTO Function { get; set; }

        #endregion
    }

}
