//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 26/03/2015 16:15:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class VProductSpecificationDTO
    {
        #region Constructors
  
        public VProductSpecificationDTO() {
        }

        public VProductSpecificationDTO(global::System.Guid productID, int productVersionID, string specificationName, string specificationDescription, global::System.Nullable<int> specificationDisplayOrder, bool isMandatory, bool isMultiSelect, bool isPreSelected, int minimumSelectionLimit, int maximumSelectionLimit, bool isUserDefined, bool isPriceDriven, global::System.Guid productSpecificationAttributeOptionID, global::System.Nullable<decimal> specDefaultOptionPriceAdjustement, global::System.Nullable<decimal> specDefaultOptionCost, global::System.Nullable<decimal> specDefaultOptionDefaultValue, global::System.Nullable<int> specDefaultOptionDefaultQuantity) {

          this.ProductID = productID;
          this.ProductVersionID = productVersionID;
          this.SpecificationName = specificationName;
          this.SpecificationDescription = specificationDescription;
          this.SpecificationDisplayOrder = specificationDisplayOrder;
          this.IsMandatory = isMandatory;
          this.IsMultiSelect = isMultiSelect;
          this.IsPreSelected = isPreSelected;
          this.MinimumSelectionLimit = minimumSelectionLimit;
          this.MaximumSelectionLimit = maximumSelectionLimit;
          this.IsUserDefined = isUserDefined;
          this.IsPriceDriven = isPriceDriven;
          this.ProductSpecificationAttributeOptionID = productSpecificationAttributeOptionID;
          this.SpecDefaultOptionPriceAdjustement = specDefaultOptionPriceAdjustement;
          this.SpecDefaultOptionCost = specDefaultOptionCost;
          this.SpecDefaultOptionDefaultValue = specDefaultOptionDefaultValue;
          this.SpecDefaultOptionDefaultQuantity = specDefaultOptionDefaultQuantity;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid ProductID { get; set; }

        [DataMember]
        public int ProductVersionID { get; set; }

        [DataMember]
        public string SpecificationName { get; set; }

        [DataMember]
        public string SpecificationDescription { get; set; }

        [DataMember]
        public global::System.Nullable<int> SpecificationDisplayOrder { get; set; }

        [DataMember]
        public bool IsMandatory { get; set; }

        [DataMember]
        public bool IsMultiSelect { get; set; }

        [DataMember]
        public bool IsPreSelected { get; set; }

        [DataMember]
        public int MinimumSelectionLimit { get; set; }

        [DataMember]
        public int MaximumSelectionLimit { get; set; }

        [DataMember]
        public bool IsUserDefined { get; set; }

        [DataMember]
        public bool IsPriceDriven { get; set; }

        [DataMember]
        public global::System.Guid ProductSpecificationAttributeOptionID { get; set; }

        [DataMember]
        public global::System.Nullable<decimal> SpecDefaultOptionPriceAdjustement { get; set; }

        [DataMember]
        public global::System.Nullable<decimal> SpecDefaultOptionCost { get; set; }

        [DataMember]
        public global::System.Nullable<decimal> SpecDefaultOptionDefaultValue { get; set; }

        [DataMember]
        public global::System.Nullable<int> SpecDefaultOptionDefaultQuantity { get; set; }

        #endregion
    }

}
