//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 18/03/2015 19:00:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class VWorkflowTreeDTO
    {
        #region Constructors
  
        public VWorkflowTreeDTO() {
        }

        public VWorkflowTreeDTO(global::System.Guid iD, string name, global::System.Guid workflowID, int workflowVersionNumber, global::System.Guid workflowTreeStructureID, global::System.Nullable<System.Guid> interfacePanelID, global::System.Nullable<int> interfacePanelVersionNumber, global::System.Nullable<int> level, global::System.Nullable<System.Guid> parentID, int itemOrder, global::System.Nullable<System.Guid> workflowActionID, bool isVisible, string conditionString) {

          this.ID = iD;
          this.Name = name;
          this.WorkflowID = workflowID;
          this.WorkflowVersionNumber = workflowVersionNumber;
          this.WorkflowTreeStructureID = workflowTreeStructureID;
          this.InterfacePanelID = interfacePanelID;
          this.InterfacePanelVersionNumber = interfacePanelVersionNumber;
          this.Level = level;
          this.ParentID = parentID;
          this.ItemOrder = itemOrder;
          this.WorkflowActionID = workflowActionID;
          this.IsVisible = isVisible;
          this.ConditionString = conditionString;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid ID { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public global::System.Guid WorkflowID { get; set; }

        [DataMember]
        public int WorkflowVersionNumber { get; set; }

        [DataMember]
        public global::System.Guid WorkflowTreeStructureID { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> InterfacePanelID { get; set; }

        [DataMember]
        public global::System.Nullable<int> InterfacePanelVersionNumber { get; set; }

        [DataMember]
        public global::System.Nullable<int> Level { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> ParentID { get; set; }

        [DataMember]
        public int ItemOrder { get; set; }

        [DataMember]
        public global::System.Nullable<System.Guid> WorkflowActionID { get; set; }

        [DataMember]
        public bool IsVisible { get; set; }

        [DataMember]
        public string ConditionString { get; set; }

        #endregion
    }

}
