//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 6/10/2014 2:36:07 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities.DTO
{

    [DataContractAttribute(IsReference=true)]
    public partial class WorkflowActivityTemplateDTO
    {
        #region Constructors
  
        public WorkflowActivityTemplateDTO() {
        }

        public WorkflowActivityTemplateDTO(global::System.Guid workflowActivityTemplateID, global::System.Guid workflowTemplateID, int workflowTemplateVersionNumber, string name, string description, bool isActive, bool isDeleted, List<WorkflowActivityActionTemplateDTO> workflowActivityActionTemplates, WorkflowTemplateDTO workflowTemplate, List<WorkflowStateActivityTemplateDTO> workflowStateActivityTemplates, List<WorkflowStateActivityActionHierarchyTemplateDTO> workflowStateActivityActionHierarchyTemplates) {

          this.WorkflowActivityTemplateID = workflowActivityTemplateID;
          this.WorkflowTemplateID = workflowTemplateID;
          this.WorkflowTemplateVersionNumber = workflowTemplateVersionNumber;
          this.Name = name;
          this.Description = description;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.WorkflowActivityActionTemplates = workflowActivityActionTemplates;
          this.WorkflowTemplate = workflowTemplate;
          this.WorkflowStateActivityTemplates = workflowStateActivityTemplates;
          this.WorkflowStateActivityActionHierarchyTemplates = workflowStateActivityActionHierarchyTemplates;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid WorkflowActivityTemplateID { get; set; }

        [DataMember]
        public global::System.Guid WorkflowTemplateID { get; set; }

        [DataMember]
        public int WorkflowTemplateVersionNumber { get; set; }

        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string Description { get; set; }

        [DataMember]
        public bool IsActive { get; set; }

        [DataMember]
        public bool IsDeleted { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public List<WorkflowActivityActionTemplateDTO> WorkflowActivityActionTemplates { get; set; }

        [DataMember]
        public WorkflowTemplateDTO WorkflowTemplate { get; set; }

        [DataMember]
        public List<WorkflowStateActivityTemplateDTO> WorkflowStateActivityTemplates { get; set; }

        [DataMember]
        public List<WorkflowStateActivityActionHierarchyTemplateDTO> WorkflowStateActivityActionHierarchyTemplates { get; set; }

        #endregion
    }

}
