//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 26/03/2015 16:15:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Bec.TargetFramework.Entities
{

    [DataContractAttribute(IsReference=true)]
    [System.Serializable]
    public partial class WorkflowActionParameterNotificationConstructDTO
    {
        #region Constructors
  
        public WorkflowActionParameterNotificationConstructDTO() {
        }

        public WorkflowActionParameterNotificationConstructDTO(global::System.Guid workflowActionParameterNotificationConstructID, global::System.Guid workflowActionParameterNotificationConstructTemplateID, global::System.Guid workflowActionID, global::System.Guid workflowParameterID, global::System.Guid workflowID, int workflowVersionNumber, global::System.Guid notificationConstructID, int organisationTypeID, global::System.Guid userTypeID, int order, global::System.Nullable<bool> isActive, global::System.Nullable<bool> isDeleted, global::System.Nullable<int> workflowActionParameterNotificationConstructVersionNumber, int notificationConstructVersionNumber, int workflowActionParameterNotificationConstructTemplateVersion, NotificationConstructDTO notificationConstruct) {

          this.WorkflowActionParameterNotificationConstructID = workflowActionParameterNotificationConstructID;
          this.WorkflowActionParameterNotificationConstructTemplateID = workflowActionParameterNotificationConstructTemplateID;
          this.WorkflowActionID = workflowActionID;
          this.WorkflowParameterID = workflowParameterID;
          this.WorkflowID = workflowID;
          this.WorkflowVersionNumber = workflowVersionNumber;
          this.NotificationConstructID = notificationConstructID;
          this.OrganisationTypeID = organisationTypeID;
          this.UserTypeID = userTypeID;
          this.Order = order;
          this.IsActive = isActive;
          this.IsDeleted = isDeleted;
          this.WorkflowActionParameterNotificationConstructVersionNumber = workflowActionParameterNotificationConstructVersionNumber;
          this.NotificationConstructVersionNumber = notificationConstructVersionNumber;
          this.WorkflowActionParameterNotificationConstructTemplateVersion = workflowActionParameterNotificationConstructTemplateVersion;
          this.NotificationConstruct = notificationConstruct;
        }

        #endregion

        #region Properties

        [DataMember]
        public global::System.Guid WorkflowActionParameterNotificationConstructID { get; set; }

        [DataMember]
        public global::System.Guid WorkflowActionParameterNotificationConstructTemplateID { get; set; }

        [DataMember]
        public global::System.Guid WorkflowActionID { get; set; }

        [DataMember]
        public global::System.Guid WorkflowParameterID { get; set; }

        [DataMember]
        public global::System.Guid WorkflowID { get; set; }

        [DataMember]
        public int WorkflowVersionNumber { get; set; }

        [DataMember]
        public global::System.Guid NotificationConstructID { get; set; }

        [DataMember]
        public int OrganisationTypeID { get; set; }

        [DataMember]
        public global::System.Guid UserTypeID { get; set; }

        [DataMember]
        public int Order { get; set; }

        [DataMember]
        public global::System.Nullable<bool> IsActive { get; set; }

        [DataMember]
        public global::System.Nullable<bool> IsDeleted { get; set; }

        [DataMember]
        public global::System.Nullable<int> WorkflowActionParameterNotificationConstructVersionNumber { get; set; }

        [DataMember]
        public int NotificationConstructVersionNumber { get; set; }

        [DataMember]
        public int WorkflowActionParameterNotificationConstructTemplateVersion { get; set; }

        #endregion

        #region Navigation Properties

        [DataMember]
        public NotificationConstructDTO NotificationConstruct { get; set; }

        #endregion
    }

}
