//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.UserAccountOrganisation in the schema.
    /// </summary>
    [System.Serializable]
    public partial class UserAccountOrganisation    {

        public UserAccountOrganisation()
        {
          this.IsActive = true;
          this.IsDeleted = false;
          this.PinAttempts = 0;
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for UserID in the schema.
        /// </summary>
        public virtual global::System.Guid UserID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrganisationUnitID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> OrganisationUnitID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrganisationID in the schema.
        /// </summary>
        public virtual global::System.Guid OrganisationID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for JobTitle in the schema.
        /// </summary>
        public virtual string JobTitle
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NickName in the schema.
        /// </summary>
        public virtual string NickName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        public virtual bool IsActive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        public virtual bool IsDeleted
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserSubTypeID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> UserSubTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserCategoryID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> UserCategoryID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserAccountOrganisationID in the schema.
        /// </summary>
        public virtual global::System.Guid UserAccountOrganisationID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserJobTypeID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> UserJobTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PrimaryContactID in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.Guid> PrimaryContactID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserTypeID in the schema.
        /// </summary>
        public virtual global::System.Guid UserTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ParentID in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.Guid> ParentID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PinCode in the schema.
        /// </summary>
        public virtual string PinCode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PinCreated in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> PinCreated
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PinAttempts in the schema.
        /// </summary>
        public virtual short PinAttempts
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for OrganisationUnit in the schema.
        /// </summary>
        public virtual OrganisationUnit OrganisationUnit
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserType in the schema.
        /// </summary>
        public virtual UserType UserType
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserAccount in the schema.
        /// </summary>
        public virtual UserAccount UserAccount
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserAccountOrganisationTeams in the schema.
        /// </summary>
        public virtual ICollection<UserAccountOrganisationTeam> UserAccountOrganisationTeams
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserAccountOrganisationRoles in the schema.
        /// </summary>
        public virtual ICollection<UserAccountOrganisationRole> UserAccountOrganisationRoles
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserAccountOrganisationGroups in the schema.
        /// </summary>
        public virtual ICollection<UserAccountOrganisationGroup> UserAccountOrganisationGroups
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for UserAccountOrganisationStatus in the schema.
        /// </summary>
        public virtual ICollection<UserAccountOrganisationStatus> UserAccountOrganisationStatus
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for NotificationRecipients in the schema.
        /// </summary>
        public virtual ICollection<NotificationRecipient> NotificationRecipients
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for ShoppingCarts in the schema.
        /// </summary>
        public virtual ICollection<ShoppingCart> ShoppingCarts
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        public virtual ICollection<Invoice> Invoices
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public virtual Contact Contact
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Organisation in the schema.
        /// </summary>
        public virtual Organisation Organisation
        {
            get;
            set;
        }

        #endregion
    }

}
