//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.ArtefactStatusTypeTemplate in the schema.
    /// </summary>
    [System.Serializable]
    public partial class ArtefactStatusTypeTemplate    {

        public ArtefactStatusTypeTemplate()
        {
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for ArtefactTemplateID in the schema.
        /// </summary>
        public virtual global::System.Guid ArtefactTemplateID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ArtefactTemplateVersionNumber in the schema.
        /// </summary>
        public virtual int ArtefactTemplateVersionNumber
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for StatusTypeTemplateID in the schema.
        /// </summary>
        public virtual global::System.Guid StatusTypeTemplateID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for StatusTypeTemplateVersionNumber in the schema.
        /// </summary>
        public virtual int StatusTypeTemplateVersionNumber
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for ArtefactTemplate in the schema.
        /// </summary>
        public virtual ArtefactTemplate ArtefactTemplate
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for StatusTypeTemplate in the schema.
        /// </summary>
        public virtual StatusTypeTemplate StatusTypeTemplate
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for ArtefactDependencyStatusTypeTemplates in the schema.
        /// </summary>
        public virtual ICollection<ArtefactDependencyStatusTypeTemplate> ArtefactDependencyStatusTypeTemplates
        {
            get;
            set;
        }

        #endregion
    }

}
