//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.HelpPage in the schema.
    /// </summary>
    [System.Serializable]
    public partial class HelpPage    {

        public HelpPage()
        {
          this.IsActive = true;
          this.IsDeleted = false;
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for HelpPageID in the schema.
        /// </summary>
        public virtual global::System.Guid HelpPageID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PageName in the schema.
        /// </summary>
        public virtual string PageName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PageUrl in the schema.
        /// </summary>
        public virtual string PageUrl
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for HelpPageTypeId in the schema.
        /// </summary>
        public virtual int HelpPageTypeId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedOn in the schema.
        /// </summary>
        public virtual global::System.DateTime CreatedOn
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedOn in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> ModifiedOn
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CreatedBy in the schema.
        /// </summary>
        public virtual string CreatedBy
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        public virtual bool IsActive
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IsDeleted in the schema.
        /// </summary>
        public virtual bool IsDeleted
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ModifiedBy in the schema.
        /// </summary>
        public virtual string ModifiedBy
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for HelpPageItems in the schema.
        /// </summary>
        public virtual ICollection<HelpPageItem> HelpPageItems
        {
            get;
            set;
        }

        #endregion
    }

}
