//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace Bec.TargetFramework.Data
{

    /// <summary>
    /// There are no comments for Bec.TargetFramework.Data.UserAccountAddress in the schema.
    /// </summary>
    [System.Serializable]
    public partial class UserAccountAddress    {

        public UserAccountAddress()
        {
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for UserAccountAddressId in the schema.
        /// </summary>
        public virtual global::System.Guid UserAccountAddressId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UserAccountId in the schema.
        /// </summary>
        public virtual global::System.Guid UserAccountId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for AddressId in the schema.
        /// </summary>
        public virtual global::System.Guid AddressId
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for UserAccount in the schema.
        /// </summary>
        public virtual UserAccount UserAccount
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public virtual Address Address
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for SmsUserAccountOrganisationTransactions in the schema.
        /// </summary>
        public virtual ICollection<SmsUserAccountOrganisationTransaction> SmsUserAccountOrganisationTransactions
        {
            get;
            set;
        }

        #endregion
    }

}
