/* Data for the 'public.ErrorCode' table  (Records 1 - 113) */

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'518db9a2-4df0-11e4-a192-0b7e7f50a964', E'1', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'SGS_RC_DECLINED', E'1.     This gateway has declined the transaction.  This could be any gateway, i.e. EFS, Telecheck, or FDI', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'518ecb1c-4df0-11e4-b94e-571f26f96a13', E'2', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'SGS_RC_REFERRAL', E'1.     The processor requires a Voice Authorization.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519051a8-4df0-11e4-9d1d-535cc5a29b51', E'100', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'SGS_RC_INTERNAL_ERROR', E'1.     This is an internal error', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5191b124-4df0-11e4-84ad-2ba9b545370d', E'1003', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'', E'1.     This happens when the comments field is too long or contains invalid characters.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5192749c-4df0-11e4-ab7a-8fc358113511', E'2000', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'SGS_RC_GW_GENERALERROR', E'1.     The error message depends on the response from the gateway.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51935ef2-4df0-11e4-9e74-177575cf0738', E'2100', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_GW_NETWORKERROR', E'1.     This can happen when there is a communication\\nerror at EFS.\\n2.     This can happen when the gateways web server times out.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5194498e-4df0-11e4-ba9f-7f76041a21cc', E'2200', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_GW_CONFIGURATIONERROR', E'1.     This can happen when there is an authentication error at EFS.\\n2.     This can happen when there is a configuration error with SGS server - HTTP Error Response Code.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519533b2-4df0-11e4-b77d-6f30c80ec46e', E'2300', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_GW_VALIDATIONERROR', E'1.     The error message depends on the response from the gateway or the basic fraud rule that is triggered.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51961e12-4df0-11e4-b992-73756a775d9c', E'2301', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_GW_VALIDATIONERROR_FORMAT', E'1.     Either missing or incorrectly formatted data entered into the specific fields named can cause this error.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51972f78-4df0-11e4-ac55-eb416ae454d2', E'2302', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_GW_VALIDATIONERROR_INVALIDEXPIRATIONDATE', E'1.     Self-explanatory', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5197f2e6-4df0-11e4-9a18-bfca51a354ae', E'2303', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_GW_VALIDATIONERROR_CREDITCARDLUHNFAILED', E'1.     Self-explanatory', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5198b62c-4df0-11e4-a363-dfe90e1c42cc', E'2304', E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', E'eSGS_RC_GW_VALIDATIONERROR_CREDITCARDEXPIRED', E'', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'5199a082-4df0-11e4-965a-5784db7a221a', E'5000', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_DB_GENERALERROR', E'1.     Typically, this occurs when the MAXLENGTH\\nparameter for one or more XML fields has been surpassed.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519a63f0-4df0-11e4-b7ff-a3078b4ee1ee', E'5001', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_DB_MISSINGDATA', E'1. Self-Explanatory', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519b272c-4df0-11e4-a4f7-7be6fa6c2ed7', E'5002', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_DB_DATANOTFOUND', E'1.  Missing, incomplete, or  invalid Order or Merchant  data on merchant  configuration file or  database ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519c389c-4df0-11e4-87c6-5701c17d5d81', E'5003', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'eSGS_RC_DB_DUPLICATE_ORDER', E'1.  The transaction must have  a unique order id number. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519cfbe2-4df0-11e4-b6e2-b305dcb6d492', E'5004', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'eSGS_RC_DB_DUPLICATE_TRANSACTION', E'1.  The transaction must have  a unique order id number. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519dbf32-4df0-11e4-bc9f-43d24ccdb9c0', E'5005', E'Form validation should prevent this, however:\\nYour payment has been declined as the details provided are invalid. Please check these details and try again.\\n', E'Form validation should prevent this, however:\\nYour payment has been declined as the details provided are invalid. Please check these details and try again.\\n', E'eSGS_RC_DB_FRAUD', E'1.  Self-explanatory errors -  missing or incomplete data  from XML or merchant  config. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'519f45dc-4df0-11e4-ae0b-a7f832a01f68', E'5006', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_DB_TIMEOUTERROR', E'1.  There was a timeout when  trying to access the  database. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a0092c-4df0-11e4-be61-c3305581f6c3', E'5007', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_DB_NETWORKERROR', E'1.  There was a network error  accessing the database. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a11aa6-4df0-11e4-b324-3f48e8ed249d', E'5008', E'N/A', E'N/A', E'eSGS_RC_DB_CANTVOID', E'1.  There is a corresponding  return for this transaction  pending  2.  This must be VOIDED  before the transaction can  be voided ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a20510-4df0-11e4-8a44-9b5fd7089482', E'5150', E'N/A', E'N/A', E'eSGS_RC_DB_RECURRINGPAYMENT', E'1.  The PB details are missing  info necessary to complete  PB trans, Transaction was  issued as a SALE.  2.  PB failed for missing or  invalid information. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a2c856-4df0-11e4-b2bb-b7d93d93fac3', E'5999', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_DB_UNKNOWNERROR', E'1.  unknown error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a38ba6-4df0-11e4-a57e-f37636167496', E'10101', E'N/A', E'N/A', E'eSGS_RC_REPEATVOID_BADTRANSACTIONSTATE', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a44f00-4df0-11e4-a6fe-6b5bda084f12', E'10501', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_POSTAUTH_BADTRANSACTIONTYPE', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a51250-4df0-11e4-bed8-8bf0ec8845c3', E'10502', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_POSTAUTH_BADTRANSACTIONSTATE', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a5d5a0-4df0-11e4-b9b1-1f1dd7b31774', E'10503', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eSGS_RC_POSTAUTH_INVALIDTOTAL', E'1.  Invalid XML format or  incorrect numeric value. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a698f0-4df0-11e4-9bab-83a2df0fb1cf', E'10801', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_VOID_BADTRANSACTIONSTATE', E'1.  This is an internal error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a73530-4df0-11e4-a288-63345bc87d58', E'11001', E'N/A', E'N/A', E'eSGS_RC_REPEATREVERSAL_BADTRANSACTIONSTATE', E'1.  Settlement Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a81f90-4df0-11e4-890b-13ddb0e0f711', E'11101', E'N/A', E'N/A', E'eSGS_RC_REPEATCAPTURE_BADTRANSACTIONSTATE', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a8e2e0-4df0-11e4-b86b-dbc16b6aaf5f', E'11201', E'N/A', E'N/A', E'eSGS_RC_PARTIALRETURN_BADTRANSACTIONSTATE', E'1.  A transaction with a  previous partial return will  not allow another return. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51a9a630-4df0-11e4-9d69-f7386eaea1b0', E'11202', E'N/A', E'N/A', E'Not authorized to run a Credit Transaction', E'1.  Enable Credit feature and  have them resend the  transaction ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51aa9090-4df0-11e4-a75f-bbf8329b5a4a', E'20000', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_UNEXPECTED_ERROR', E'1.  Unexpected error - System  Response error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51ab53ea-4df0-11e4-8da5-9bd2674206c7', E'20001', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_OUT_OF_MEMORY,', E'1.  Out of Memory Error. -  System Response Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51ac1726-4df0-11e4-bb80-73a54ab430a1', E'20002', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_ERROR_READING_DATA,', E'1.  Connection to  Host/Database error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51acda94-4df0-11e4-8de1-338d10288dc2', E'20003', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eLSGS_RC_INVALID_CHAR_IN_XML,', E'1.  One of these characters is  being passed: '' \\\" < > & ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51ad9de4-4df0-11e4-81dd-03f66f42d454', E'20004', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_MERCHANT_CONFIG_FILE_MISSING,', E'1.  Using incorrect storename,  hostname, or combination ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51ae6134-4df0-11e4-a64a-efbdd594cbdd', E'20005', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_CONTACT_NAME_MISMATCH,', E'1.  Invalid Contact Name Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51af99aa-4df0-11e4-9415-ffc134b5c794', E'20006', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'', E'1.  Invalid Contact Name Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b05d04-4df0-11e4-bcff-5bc9201f6699', E'20007', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_INVALID_MERCHANT_ID,', E'1.  Missing or incomplete  Merchant Data ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b1475a-4df0-11e4-b7de-278aaec9a17c', E'20008', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_ORDER_ID_REQUIRED,', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b20aaa-4df0-11e4-8709-43196a17fe62', E'20009', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eLSGS_RC_CREDITCARD_AND_CHECK,', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b2d9b2-4df0-11e4-9f6b-43d54c202c7c', E'20010', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eLSGS_RC_NO_CREDITCARD_CHECK,', E'1.  Self-Explanatory ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b396c2-4df0-11e4-ac91-9f8f045651fd', E'20011', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_HTTP_ERROR_SGS,', E'1.  Referral or System  Response Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b45a12-4df0-11e4-ae76-631244b187b9', E'20012', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_COMMUNICATION_ERROR_SGS,', E'1.  Processor System  Response Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b51d6c-4df0-11e4-909c-1715a380b0ca', E'20013', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_UNEXPECTED_SGS_RESPONSE,', E'1.  Processor System  Response Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b5e0b2-4df0-11e4-8e45-375ef80d258d', E'20014', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_RESPONSE_PARSE_ERROR_SGS,', E'1.  Processor System  Response Error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b6a402-4df0-11e4-8bfa-03e6d9ee739f', E'20015', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_INVALID_OPTION_RESULT,', E'1.  Invalid Order Result value  set - Must be LIVE, GOOD,  DUPLICATE, or DECLINE  only. ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b7675c-4df0-11e4-bdc7-5f81504a4691', E'20016', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'eLSGS_RC_SIMULATION_DECLINED,', E'1.  Declined ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b851c6-4df0-11e4-83a5-679441e93d28', E'20017', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'eLSGS_RC_SIMULATION_DUPLICATE,', E'1.  Duplicate Transaction ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b91516-4df0-11e4-8cab-8f6058cc3a23', E'20018', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eLSGS_RC_UNKNOWNERROR', E'1.  unknown error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'51b9b14c-4df0-11e4-acd2-37532c20d3e0', E'32000', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'eSGS_RC_UNKNOWNERROR', E'1.  unknown error ', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'70486b08-4df0-11e4-b6c6-3712cc8b66de', E'1003', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'', E'1.     This happens when the comments field is too long or contains invalid characters.', 1000001, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21756570-4df1-11e4-a87c-ab055de0ee0e', E'0', E'The transaction was successful', E'None', E'Transaction Approved', E'The transaction was successful', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217676fe-4df1-11e4-a885-2f6914bbc49d', E'1', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Refer to Issuer', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21778d1e-4df1-11e4-b656-e3c56b02cae9', E'2', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Refer to Issuer, special', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21785a14-4df1-11e4-bb65-2345af8ba1d5', E'3', E'The Merchant ID is invalid, you should contact your Bank and ensure you have provided the correct Merchant Account Number toÂ PayChoice', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'No Merchant', E'The Merchant ID is invalid, you should contact your Bank and ensure you have provided the correct Merchant Account Number toÂ PayChoice', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21791e90-4df1-11e4-9cbc-ffe1f2537e59', E'4', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen). The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Pick Up Card', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen). The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217aa490-4df1-11e4-a00b-e791f3591b5d', E'5', E'The customer''s bank has declined the transaction as the credit card number has failed a security check, or the funds have been frozen or depleted. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Do Not Honour', E'The customer''s bank has declined the transaction as the credit card number has failed a security check, or the funds have been frozen or depleted. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217b8efa-4df1-11e4-959d-c3a9b06e8e0b', E'6', E'The customer''s bank (Card Issuer) has declined the transaction as there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Error', E'The customer''s bank (Card Issuer) has declined the transaction as there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217c524a-4df1-11e4-9b0a-af0e9ffe5c31', E'7', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Pick Up Card, Special', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217d159a-4df1-11e4-b873-3f711a2503f8', E'8', E'The transaction was successful', E'None', E'Honour With Identification', E'The transaction was successful', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217dd8ea-4df1-11e4-af50-8f8838a0db2f', E'9', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Request In Progress', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217eea5a-4df1-11e4-b540-23fc67508917', E'10', E'The transaction was successful', E'None', E'Approved For Partial Amount', E'The transaction was successful', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'217fc6a0-4df1-11e4-bd6f-eb29ac6b485d', E'11', E'The transaction was successful', E'None', E'Approved, VIP', E'The transaction was successful', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218092e2-4df1-11e4-910f-1b4c53851836', E'12', E'The customer''s bank (Card Issuer) has declined the transaction because of an invalid format or field. Check the transaction information and try processing the transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Invalid Transaction', E'The customer''s bank (Card Issuer) has declined the transaction because of an invalid format or field. Check the transaction information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218170c2-4df1-11e4-8256-df22cdb3c227', E'13', E'An invalid character (e.g. a dollar sign or a space) may be being passed to the gateway. Check your website''s code.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Invalid Amount', E'An invalid character (e.g. a dollar sign or a space) may be being passed to the gateway. Check your website''s code.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21823408-4df1-11e4-bdbd-87047caa244e', E'14', E'The customer''s bank (Card Issuer) has declined the transaction as the Credit Card number does not exist. Check the credit card information and try processing the transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Invalid Card Number', E'The customer''s bank (Card Issuer) has declined the transaction as the Credit Card number does not exist. Check the credit card information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2182f762-4df1-11e4-b285-bffa81d00b19', E'15', E'The customer''s bank (Card Issuer) does not exist. Check the credit card information and try processing the transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'No Issuer', E'The customer''s bank (Card Issuer) does not exist. Check the credit card information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2183e500-4df1-11e4-88bb-6f2a9ec1beb1', E'16', E'The transaction was successful', E'None', E'Approved, Update Track 3', E'The transaction was successful', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2184acc4-4df1-11e4-b93a-5721afa8810a', E'19', E'The transaction has not been processed and the customer should attempt to process the transaction again.', E'We have been unable to process your payment at this time. Please check your details and try again. You have not been charged.', E'Re-enter Last Transaction', E'The transaction has not been processed and the customer should attempt to process the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2185499a-4df1-11e4-842b-075ac82b4e29', E'21', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', E'Your card issuer has indicated that there is a problem with this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Action Taken', E'The customer''s bank (Card Issuer) has indicated there is a problem with the credit card number. The customer should contact their bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218633fa-4df1-11e4-9619-8f00d976449b', E'22', E'The customer''s bank (Card Issuer) cannot be contacted during the transaction. The customer should check the credit card information and try processing the transaction again.', E'We have been unable to process your payment at this time. Please check your details and try again. You have not been charged.', E'Suspected Malfunction', E'The customer''s bank (Card Issuer) cannot be contacted during the transaction. The customer should check the credit card information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2186f74a-4df1-11e4-a1fb-d7774e20106d', E'23', E'An unspecified error has occurred.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Unacceptable Transaction Fee', E'An unspecified error has occurred.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2187baae-4df1-11e4-a7bb-6fe95057847c', E'25', E'The customer''s bank (Card Issuer) does not recognise the credit card details. The customer should check the credit card information and try processing the transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Unable to Locate Record On File', E'The customer''s bank (Card Issuer) does not recognise the credit card details. The customer should check the credit card information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218949aa-4df1-11e4-8d07-9ba7baaa5236', E'30', E'The customer''s bank (Card Issuer) does not recognise the transaction details. The customer should check the transaction information and try processing the transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Format Error', E'The customer''s bank (Card Issuer) does not recognise the transaction details. The customer should check the transaction information and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2189e5cc-4df1-11e4-87bc-dbc88f4ddca7', E'31', E'The customer''s bank (Card Issuer) has declined the transaction as it does not allow transactions originating through mail / telephone, fax, email or Internet orders. This error is associated customers attempting to use a Discover Card. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Bank Not Supported By Switch', E'The customer''s bank (Card Issuer) has declined the transaction as it does not allow transactions originating through mail / telephone, fax, email or Internet orders. This error is associated customers attempting to use a Discover Card. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218b4566-4df1-11e4-a104-23520aa3f24a', E'33', E'The customer''s bank (Card Issuer) has declined the transaction as Credit Card has expired or the date is incorrect. Check the expiry date in the transaction and try processing the transaction again.', E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', E'Expired Card, Capture', E'The customer''s bank (Card Issuer) has declined the transaction as Credit Card has expired or the date is incorrect. Check the expiry date in the transaction and try processing the transaction again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218c08b6-4df1-11e4-8298-038968c15a44', E'34', E'The customer''s bank (Card Issuer) has declined the transaction as there is a suspected fraud on this Credit Card number.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Suspected Fraud, Retain Card', E'The customer''s bank (Card Issuer) has declined the transaction as there is a suspected fraud on this Credit Card number.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218cf316-4df1-11e4-bdd0-dbdaa3c50955', E'35', E'The customer''s bank (Card Issuer) has declined the transaction and requested that the customer''s credit card be retained (card reported lost or stolen). The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Card Acceptor, Contact Acquirer, Retain Card', E'The customer''s bank (Card Issuer) has declined the transaction and requested that the customer''s credit card be retained (card reported lost or stolen). The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218db666-4df1-11e4-a5d3-bfcd17cddedc', E'36', E'The customer''s bank (Card Issuer) has declined the transaction and requested that the customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Restricted Card, Retain Card', E'The customer''s bank (Card Issuer) has declined the transaction and requested that the customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218e79b6-4df1-11e4-a287-8b95832008db', E'37', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Contact Acquirer Security Department, Retain Card', E'The customer''s bank (Card Issuer) has declined the transaction and requested that your customer''s credit card be retained. (card reported lost or stolen) The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'218f3d06-4df1-11e4-82ca-db13dc895cc8', E'38', E'The customer''s bank (Card Issuer) has declined the transaction as the customer has entered the incorrect PIN three times. The customer''s bank (Card Issuer) has requested you retain the credit card. The customer should use an alternate credit card and contact their bank.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'PIN Tries Exceeded, Capture', E'The customer''s bank (Card Issuer) has declined the transaction as the customer has entered the incorrect PIN three times. The customer''s bank (Card Issuer) has requested you retain the credit card. The customer should use an alternate credit card and contact their bank.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2190007e-4df1-11e4-9e78-8b1a002db974', E'39', E'The customer''s bank has declined the transaction as the Credit Card number used is not a credit account. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Credit Account', E'The customer''s bank has declined the transaction as the Credit Card number used is not a credit account. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2190c3ba-4df1-11e4-874e-337a28a01778', E'40', E'The customer''s bank (Card Issuer) has declined the transaction as it does not allow this type of transaction. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Function Not Supported', E'The customer''s bank (Card Issuer) has declined the transaction as it does not allow this type of transaction. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21916022-4df1-11e4-b0f4-9b720573d088', E'41', E'The customer''s bank (Card Issuer) has declined the transaction as the card has been reported lost. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Lost Card', E'The customer''s bank (Card Issuer) has declined the transaction as the card has been reported lost. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21922340-4df1-11e4-9a0e-c337aa873dc2', E'42', E'The customer''s bank (Card Issuer) has declined the transaction as the account type selected is not valid for this credit card number. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Universal Account', E'The customer''s bank (Card Issuer) has declined the transaction as the account type selected is not valid for this credit card number. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2192e690-4df1-11e4-a928-dfe2ffb9ccc4', E'43', E'The customer''s bank (Card Issuer) has declined the transaction as the card has been reported stolen. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Stolen Card', E'The customer''s bank (Card Issuer) has declined the transaction as the card has been reported stolen. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2193aa26-4df1-11e4-9baf-ff090cc2a123', E'44', E'The customer''s bank (Card Issuer) has declined the transaction as the account type selected is not valid for this credit card number. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Investment Account', E'The customer''s bank (Card Issuer) has declined the transaction as the account type selected is not valid for this credit card number. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2194bb50-4df1-11e4-89d8-035f19234d33', E'51', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card does not have sufficient funds. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Insufficient Funds', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card does not have sufficient funds. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2195f3da-4df1-11e4-b4f2-e79576753e4e', E'52', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card number is associated to a cheque account that does not exist. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Cheque Account', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card number is associated to a cheque account that does not exist. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2197055e-4df1-11e4-b830-03a50af1e48b', E'53', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card number is associated to a savings account that does not exist. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Savings Account', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card number is associated to a savings account that does not exist. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2197a1b2-4df1-11e4-b3d2-db29c0bc2c0e', E'54', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card appears to have expired. The customer should check the expiry date entered and try again, or use an alternate credit card.', E'Your card has expired. Please check your details and resbmit or try another card. You have not been charged.', E'Expired Card', E'The customer''s bank (Card Issuer) has declined the transaction as the credit card appears to have expired. The customer should check the expiry date entered and try again, or use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2198742a-4df1-11e4-8ecf-f39094af9877', E'55', E'The customer''s bank (Card Issuer) has declined the transaction as the customer has entered an incorrect PIN. The customer should re-enter their PIN, otherwise use an alternate credit card.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Incorrect PIN', E'The customer''s bank (Card Issuer) has declined the transaction as the customer has entered an incorrect PIN. The customer should re-enter their PIN, otherwise use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219937de-4df1-11e4-a245-c3ced98c7214', E'56', E'The Customer''s bank has declined the transaction as the credit card number does not exist. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'No Card Record', E'The Customer''s bank has declined the transaction as the credit card number does not exist. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'2199fb38-4df1-11e4-b51f-e76c06953369', E'57', E'The Customer''s bank has declined the transaction as this credit card cannot be used for this type of transaction. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Function Not Permitted to Cardholder', E'The Customer''s bank has declined the transaction as this credit card cannot be used for this type of transaction. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219a976e-4df1-11e4-82f2-ffe9d8d1fda4', E'58', E'The Customer''s bank has declined the transaction as this credit card cannot be used for this type of transaction. This may be associated with a test credit card number. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Function Not Permitted to Terminal', E'The Customer''s bank has declined the transaction as this credit card cannot be used for this type of transaction. This may be associated with a test credit card number. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219bcff8-4df1-11e4-b453-87fd1fd047c6', E'59', E'The customer''s bank has declined this transaction as the credit card appears to be fraudulent.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Suspected Fraud', E'The customer''s bank has declined this transaction as the credit card appears to be fraudulent.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219c9348-4df1-11e4-a7ca-9fd43a548db6', E'60', E'The customer''s bank (card issuer) has declined the transaction. The customer should contact their bank and retry the transaction.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Acceptor Contact Acquirer', E'The customer''s bank (card issuer) has declined the transaction. The customer should contact their bank and retry the transaction.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219d56ac-4df1-11e4-b8a9-83e4dc20f23b', E'61', E'The customer''s bank has declined the transaction as it will exceed the customer''s card limit. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Exceeds Withdrawal Limit', E'The customer''s bank has declined the transaction as it will exceed the customer''s card limit. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219e19e8-4df1-11e4-8bc6-079d8436c8f0', E'62', E'The customer''s bank has declined the transaction as the credit card has some restrictions. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Restricted Card', E'The customer''s bank has declined the transaction as the credit card has some restrictions. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219edd38-4df1-11e4-a683-3bfe89a1ae74', E'63', E'The customer''s bank has declined the transaction. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Security Violation', E'The customer''s bank has declined the transaction. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'219fa290-4df1-11e4-ace4-271bc1847cd7', E'64', E'The customer''s bank has declined the transaction due to the amount attempting to be processed. The customer should check the transaction amount and try again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Original Amount Incorrect', E'The customer''s bank has declined the transaction due to the amount attempting to be processed. The customer should check the transaction amount and try again.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a08520-4df1-11e4-9c56-7f2685723708', E'66', E'The customer''s bank has declined the transaction and request the Merchant to contact the bank. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Acceptor Contact Acquirer, Security', E'The customer''s bank has declined the transaction and request the Merchant to contact the bank. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a148f2-4df1-11e4-a6e2-6f10f19cbadc', E'67', E'The customer''s bank has declined the transaction as the card is suspected to be counterfeit. The customer''s bank (Card Issuer) has requested that your customer''s credit card be retained. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Capture Card', E'The customer''s bank has declined the transaction as the card is suspected to be counterfeit. The customer''s bank (Card Issuer) has requested that your customer''s credit card be retained. The customer should use an alternate credit card.', 1000002, 1001001);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a20c4c-4df1-11e4-9db0-b3bbb61b25a7', E'75', E'The customer''s bank has declined the transaction as the customer has entered the incorrect PIN more than three times. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'PIN Tries Exceeded', E'The customer''s bank has declined the transaction as the customer has entered the incorrect PIN more than three times. The customer should use an alternate credit card.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a2a878-4df1-11e4-aa82-b78d1f2135d1', E'82', E'The customer''s bank has declined the transaction as the CVV is incorrect. The customer should check the CVV details and try again. If not successful, the customer should use an alternate credit card.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'CVV Validation Error', E'The customer''s bank has declined the transaction as the CVV is incorrect. The customer should check the CVV details and try again. If not successful, the customer should use an alternate credit card.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a36bc8-4df1-11e4-a092-9fecf2b08b2e', E'90', E'The customer''s bank is temporarily not able to process this customer''s credit card. The customer should attempt to process this transaction again.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Cutoff In Progress', E'The customer''s bank is temporarily not able to process this customer''s credit card. The customer should attempt to process this transaction again.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a42f22-4df1-11e4-aa38-63ce15f13908', E'91', E'The customer''s bank is unable to be contacted to authorise the transaction. The customer should attempt to process this transaction again.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'Card Issuer Unavailable', E'The customer''s bank is unable to be contacted to authorise the transaction. The customer should attempt to process this transaction again.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a4f268-4df1-11e4-b952-23c407598a93', E'92', E'The customer''s bank cannot be found for routing. This response code is often returned when the customer is using a test credit card number. The customer should attempt to process this transaction again.', E'Your payment has been declined as the details provided are invalid. Please check these details and try again.', E'Unable To Route Transaction', E'The customer''s bank cannot be found for routing. This response code is often returned when the customer is using a test credit card number. The customer should attempt to process this transaction again.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a5b5b8-4df1-11e4-a4ab-5f1f616a505f', E'93', E'The customer''s bank has declined the transaction and request the customer to contact their bank. The customer should use an alternate credit card.', E'Your card issuer has declined payment using this card. Please contact your card issuer to resolve this issue. To make a payment now you will need to use an alternate card', E'Cannot Complete, Violation Of The Law', E'The customer''s bank has declined the transaction and request the customer to contact their bank. The customer should use an alternate credit card.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a67908-4df1-11e4-a616-5ba4036e13f8', E'94', E'The customer''s bank has declined the transaction as this transaction appears to be a duplicate transmission. No action required.', E'Your payment has been declined as they match those of another recent transaction. Please contact support@safemovescheme.org for further assistance.', E'Duplicate Transaction', E'The customer''s bank has declined the transaction as this transaction appears to be a duplicate transmission. No action required.', NULL, NULL);

INSERT INTO public."ErrorCode" ("ErrorCodeID", "ErrorCode", "Explanation", "ErrorMessage", "ErrorMapping", "Notes", "ErrorCodeTypeID", "ErrorCodeCategoryID")
VALUES (E'21a76372-4df1-11e4-bdc0-1309311d1ebe', E'96', E'The customer''s bank was not able to process the transaction. The customer should attempt to process this transaction again.', E'Your payment has encountered a problem and we are unable to process your request at this time. Please try again later. You have not been charged for this payment.', E'System Error', E'The customer''s bank was not able to process the transaction. The customer should attempt to process this transaction again.', NULL, NULL);