//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 08/06/2015 16:32:47
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.SB.Entities
{

    public static partial class BusEventMessageSubscriberConverter
    {

        public static BusEventMessageSubscriberDTO ToDto(this Bec.TargetFramework.SB.Data.BusEventMessageSubscriber source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static BusEventMessageSubscriberDTO ToDtoWithRelated(this Bec.TargetFramework.SB.Data.BusEventMessageSubscriber source, int level)
        {
            if (source == null)
              return null;

            var target = new BusEventMessageSubscriberDTO();

            // Properties
            target.BusEventMessageSubscriberID = source.BusEventMessageSubscriberID;
            target.Name = source.Name;
            target.ObjectName = source.ObjectName;
            target.ObjectAssembly = source.ObjectAssembly;
            target.DefaultMessageSubscriberFilter = source.DefaultMessageSubscriberFilter;

            // Navigation Properties
            if (level > 0) {
              target.BusEventBusEventMessageSubscribers = source.BusEventBusEventMessageSubscribers.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Bec.TargetFramework.SB.Data.BusEventMessageSubscriber ToEntity(this BusEventMessageSubscriberDTO source)
        {
            if (source == null)
              return null;

            var target = new Bec.TargetFramework.SB.Data.BusEventMessageSubscriber();

            // Properties
            target.BusEventMessageSubscriberID = source.BusEventMessageSubscriberID;
            target.Name = source.Name;
            target.ObjectName = source.ObjectName;
            target.ObjectAssembly = source.ObjectAssembly;
            target.DefaultMessageSubscriberFilter = source.DefaultMessageSubscriberFilter;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<BusEventMessageSubscriberDTO> ToDtos(this IEnumerable<Bec.TargetFramework.SB.Data.BusEventMessageSubscriber> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<BusEventMessageSubscriberDTO> ToDtosWithRelated(this IEnumerable<Bec.TargetFramework.SB.Data.BusEventMessageSubscriber> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Bec.TargetFramework.SB.Data.BusEventMessageSubscriber> ToEntities(this IEnumerable<BusEventMessageSubscriberDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Bec.TargetFramework.SB.Data.BusEventMessageSubscriber source, BusEventMessageSubscriberDTO target);

        static partial void OnEntityCreating(BusEventMessageSubscriberDTO source, Bec.TargetFramework.SB.Data.BusEventMessageSubscriber target);

    }

}
