//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 07/04/2015 09:50:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.Entities
{

    public static partial class ArtefactDependencyTemplateConverter
    {

        public static ArtefactDependencyTemplateDTO ToDto(this Bec.TargetFramework.Data.ArtefactDependencyTemplate source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static ArtefactDependencyTemplateDTO ToDtoWithRelated(this Bec.TargetFramework.Data.ArtefactDependencyTemplate source, int level)
        {
            if (source == null)
              return null;

            var target = new ArtefactDependencyTemplateDTO();

            // Properties
            target.ArtefactDependencyTemplateID = source.ArtefactDependencyTemplateID;
            target.ArtefactTemplateID = source.ArtefactTemplateID;
            target.ArtefactTemplateVersionNumber = source.ArtefactTemplateVersionNumber;
            target.DependencyArtefactTemplateID = source.DependencyArtefactTemplateID;
            target.DependencyArtefactTemplateVersionNumber = source.DependencyArtefactTemplateVersionNumber;
            target.IsActive = source.IsActive;
            target.IsDeleted = source.IsDeleted;

            // Navigation Properties
            if (level > 0) {
              target.ArtefactTemplate_ArtefactTemplateID_ArtefactTemplateVersionNumber = source.ArtefactTemplate_ArtefactTemplateID_ArtefactTemplateVersionNumber.ToDtoWithRelated(level - 1);
              target.ArtefactDependencies = source.ArtefactDependencies.ToDtosWithRelated(level - 1);
              target.ArtefactTemplate_DependencyArtefactTemplateID_DependencyArtefactTemplateVersionNumber = source.ArtefactTemplate_DependencyArtefactTemplateID_DependencyArtefactTemplateVersionNumber.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Bec.TargetFramework.Data.ArtefactDependencyTemplate ToEntity(this ArtefactDependencyTemplateDTO source)
        {
            if (source == null)
              return null;

            var target = new Bec.TargetFramework.Data.ArtefactDependencyTemplate();

            // Properties
            target.ArtefactDependencyTemplateID = source.ArtefactDependencyTemplateID;
            target.ArtefactTemplateID = source.ArtefactTemplateID;
            target.ArtefactTemplateVersionNumber = source.ArtefactTemplateVersionNumber;
            target.DependencyArtefactTemplateID = source.DependencyArtefactTemplateID;
            target.DependencyArtefactTemplateVersionNumber = source.DependencyArtefactTemplateVersionNumber;
            target.IsActive = source.IsActive;
            target.IsDeleted = source.IsDeleted;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<ArtefactDependencyTemplateDTO> ToDtos(this IEnumerable<Bec.TargetFramework.Data.ArtefactDependencyTemplate> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<ArtefactDependencyTemplateDTO> ToDtosWithRelated(this IEnumerable<Bec.TargetFramework.Data.ArtefactDependencyTemplate> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Bec.TargetFramework.Data.ArtefactDependencyTemplate> ToEntities(this IEnumerable<ArtefactDependencyTemplateDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Bec.TargetFramework.Data.ArtefactDependencyTemplate source, ArtefactDependencyTemplateDTO target);

        static partial void OnEntityCreating(ArtefactDependencyTemplateDTO source, Bec.TargetFramework.Data.ArtefactDependencyTemplate target);

    }

}
