//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 07/04/2015 09:00:41
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.Core.Entities
{

    public static partial class BusEventBusEventMessageSubscriberConverter
    {

        public static BusEventBusEventMessageSubscriberDTO ToDto(this TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static BusEventBusEventMessageSubscriberDTO ToDtoWithRelated(this TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber source, int level)
        {
            if (source == null)
              return null;

            var target = new BusEventBusEventMessageSubscriberDTO();

            // Properties
            target.BusEventID = source.BusEventID;
            target.BusEventMessageSubscriberID = source.BusEventMessageSubscriberID;
            target.IsActive = source.IsActive;
            target.IsDeleted = source.IsDeleted;
            target.BusEventMessageSubscriberFilter = source.BusEventMessageSubscriberFilter;

            // Navigation Properties
            if (level > 0) {
              target.BusEvent = source.BusEvent.ToDtoWithRelated(level - 1);
              target.BusEventMessageSubscriber = source.BusEventMessageSubscriber.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber ToEntity(this BusEventBusEventMessageSubscriberDTO source)
        {
            if (source == null)
              return null;

            var target = new TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber();

            // Properties
            target.BusEventID = source.BusEventID;
            target.BusEventMessageSubscriberID = source.BusEventMessageSubscriberID;
            target.IsActive = source.IsActive;
            target.IsDeleted = source.IsDeleted;
            target.BusEventMessageSubscriberFilter = source.BusEventMessageSubscriberFilter;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<BusEventBusEventMessageSubscriberDTO> ToDtos(this IEnumerable<TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<BusEventBusEventMessageSubscriberDTO> ToDtosWithRelated(this IEnumerable<TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber> ToEntities(this IEnumerable<BusEventBusEventMessageSubscriberDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber source, BusEventBusEventMessageSubscriberDTO target);

        static partial void OnEntityCreating(BusEventBusEventMessageSubscriberDTO source, TargetFrameworkCoreModel.BusEventBusEventMessageSubscriber target);

    }

}
