//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.Entities
{

    public static partial class HelpItemConverter
    {

        public static HelpItemDTO ToDto(this Bec.TargetFramework.Data.HelpItem source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static HelpItemDTO ToDtoWithRelated(this Bec.TargetFramework.Data.HelpItem source, int level)
        {
            if (source == null)
              return null;

            var target = new HelpItemDTO();

            // Properties
            target.HelpItemID = source.HelpItemID;
            target.HelpPageID = source.HelpPageID;
            target.Title = source.Title;
            target.Description = source.Description;
            target.DisplayOrder = source.DisplayOrder;
            target.Selector = source.Selector;
            target.TabContainerId = source.TabContainerId;
            target.EffectiveOn = source.EffectiveOn;
            target.Position = source.Position;
            target.CreatedOn = source.CreatedOn;
            target.ModifiedOn = source.ModifiedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedBy = source.ModifiedBy;

            // Navigation Properties
            if (level > 0) {
              target.HelpPage = source.HelpPage.ToDtoWithRelated(level - 1);
              target.HelpItemUserAccounts = source.HelpItemUserAccounts.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Bec.TargetFramework.Data.HelpItem ToEntity(this HelpItemDTO source)
        {
            if (source == null)
              return null;

            var target = new Bec.TargetFramework.Data.HelpItem();

            // Properties
            target.HelpItemID = source.HelpItemID;
            target.HelpPageID = source.HelpPageID;
            target.Title = source.Title;
            target.Description = source.Description;
            target.DisplayOrder = source.DisplayOrder;
            target.Selector = source.Selector;
            target.TabContainerId = source.TabContainerId;
            target.EffectiveOn = source.EffectiveOn;
            target.Position = source.Position;
            target.CreatedOn = source.CreatedOn;
            target.ModifiedOn = source.ModifiedOn;
            target.CreatedBy = source.CreatedBy;
            target.ModifiedBy = source.ModifiedBy;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<HelpItemDTO> ToDtos(this IEnumerable<Bec.TargetFramework.Data.HelpItem> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<HelpItemDTO> ToDtosWithRelated(this IEnumerable<Bec.TargetFramework.Data.HelpItem> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Bec.TargetFramework.Data.HelpItem> ToEntities(this IEnumerable<HelpItemDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Bec.TargetFramework.Data.HelpItem source, HelpItemDTO target);

        static partial void OnEntityCreating(HelpItemDTO source, Bec.TargetFramework.Data.HelpItem target);

    }

}
