//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.Entities
{

    public static partial class OrganisationLedgerTransactionConverter
    {

        public static OrganisationLedgerTransactionDTO ToDto(this Bec.TargetFramework.Data.OrganisationLedgerTransaction source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static OrganisationLedgerTransactionDTO ToDtoWithRelated(this Bec.TargetFramework.Data.OrganisationLedgerTransaction source, int level)
        {
            if (source == null)
              return null;

            var target = new OrganisationLedgerTransactionDTO();

            // Properties
            target.OrganisationLedgerAccountID = source.OrganisationLedgerAccountID;
            target.TransactionOrderID = source.TransactionOrderID;
            target.BalanceOn = source.BalanceOn;
            target.Amount = source.Amount;
            target.CreatedBy = source.CreatedBy;
            target.Notes = source.Notes;

            // Navigation Properties
            if (level > 0) {
              target.OrganisationLedgerAccount = source.OrganisationLedgerAccount.ToDtoWithRelated(level - 1);
              target.TransactionOrder = source.TransactionOrder.ToDtoWithRelated(level - 1);
              target.UserAccountOrganisation = source.UserAccountOrganisation.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Bec.TargetFramework.Data.OrganisationLedgerTransaction ToEntity(this OrganisationLedgerTransactionDTO source)
        {
            if (source == null)
              return null;

            var target = new Bec.TargetFramework.Data.OrganisationLedgerTransaction();

            // Properties
            target.OrganisationLedgerAccountID = source.OrganisationLedgerAccountID;
            target.TransactionOrderID = source.TransactionOrderID;
            target.BalanceOn = source.BalanceOn;
            target.Amount = source.Amount;
            target.CreatedBy = source.CreatedBy;
            target.Notes = source.Notes;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<OrganisationLedgerTransactionDTO> ToDtos(this IEnumerable<Bec.TargetFramework.Data.OrganisationLedgerTransaction> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<OrganisationLedgerTransactionDTO> ToDtosWithRelated(this IEnumerable<Bec.TargetFramework.Data.OrganisationLedgerTransaction> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Bec.TargetFramework.Data.OrganisationLedgerTransaction> ToEntities(this IEnumerable<OrganisationLedgerTransactionDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Bec.TargetFramework.Data.OrganisationLedgerTransaction source, OrganisationLedgerTransactionDTO target);

        static partial void OnEntityCreating(OrganisationLedgerTransactionDTO source, Bec.TargetFramework.Data.OrganisationLedgerTransaction target);

    }

}
