//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace Bec.TargetFramework.Entities
{

    public static partial class SmsBankAccountCheckConverter
    {

        public static SmsBankAccountCheckDTO ToDto(this Bec.TargetFramework.Data.SmsBankAccountCheck source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static SmsBankAccountCheckDTO ToDtoWithRelated(this Bec.TargetFramework.Data.SmsBankAccountCheck source, int level)
        {
            if (source == null)
              return null;

            var target = new SmsBankAccountCheckDTO();

            // Properties
            target.SmsBankAccountCheckID = source.SmsBankAccountCheckID;
            target.SmsUserAccountOrganisationTransactionID = source.SmsUserAccountOrganisationTransactionID;
            target.CheckedOn = source.CheckedOn;
            target.IsMatch = source.IsMatch;

            // Navigation Properties
            if (level > 0) {
              target.SmsUserAccountOrganisationTransaction_SmsUserAccountOrganisationTransactionID = source.SmsUserAccountOrganisationTransaction_SmsUserAccountOrganisationTransactionID.ToDtoWithRelated(level - 1);
              target.SmsUserAccountOrganisationTransactions_LatestBankAccountCheckID = source.SmsUserAccountOrganisationTransactions_LatestBankAccountCheckID.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static Bec.TargetFramework.Data.SmsBankAccountCheck ToEntity(this SmsBankAccountCheckDTO source)
        {
            if (source == null)
              return null;

            var target = new Bec.TargetFramework.Data.SmsBankAccountCheck();

            // Properties
            target.SmsBankAccountCheckID = source.SmsBankAccountCheckID;
            target.SmsUserAccountOrganisationTransactionID = source.SmsUserAccountOrganisationTransactionID;
            target.CheckedOn = source.CheckedOn;
            target.IsMatch = source.IsMatch;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<SmsBankAccountCheckDTO> ToDtos(this IEnumerable<Bec.TargetFramework.Data.SmsBankAccountCheck> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<SmsBankAccountCheckDTO> ToDtosWithRelated(this IEnumerable<Bec.TargetFramework.Data.SmsBankAccountCheck> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<Bec.TargetFramework.Data.SmsBankAccountCheck> ToEntities(this IEnumerable<SmsBankAccountCheckDTO> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(Bec.TargetFramework.Data.SmsBankAccountCheck source, SmsBankAccountCheckDTO target);

        static partial void OnEntityCreating(SmsBankAccountCheckDTO source, Bec.TargetFramework.Data.SmsBankAccountCheck target);

    }

}
